/**
 * Design: Atlas académique vivant — le contexte africain propose des questions transversales et des sources, jamais des classements simplistes.
 */
import { ArrowRight, BookOpenText, ExternalLink, Map, Scale, ShieldCheck } from "lucide-react";
import { Link } from "wouter";
import SiteShell from "@/components/SiteShell";
import PageHero from "@/components/PageHero";
import { africanThemes, resourceLinks } from "@/data/v2";

export default function Africa() {
  return <SiteShell>
    <PageHero variant="page-hero-africa" eyebrow="Contexte africain" title={<>Comprendre des enjeux<br /><em>sans réduire un continent.</em></>} description="EcoCompass propose des questions économiques transversales qui peuvent être étudiées dans plusieurs territoires africains. Elles sont des portes d’entrée pédagogiques, pas des conclusions sur des pays ou populations." aside={<div className="africa-hero-note"><Map size={21} /><b>Comparer avec prudence</b><span>Pays, année, indicateur, unité et source sont nécessaires avant toute comparaison.</span></div>} />
    <section className="bg-[#F8F5ED] py-12 lg:py-16"><div className="container"><div className="africa-principle"><Scale size={21} /><div><p className="eyebrow">Avant de comparer</p><h2>Un indicateur décrit une dimension, pas « le meilleur pays ».</h2><p>Deux valeurs ne sont comparables que si leurs définitions, périodes, unités, périmètres et sources le permettent. Une même donnée peut aussi cacher des réalités territoriales ou sociales différentes.</p></div></div><div className="mt-10 grid gap-4 md:grid-cols-2">{africanThemes.map((theme, index) => <article className="africa-theme" key={theme.title}><span>0{index + 1}</span><div><p className="eyebrow">Question d’exploration</p><h2>{theme.title}</h2><p>{theme.question}</p><div>{theme.concepts.map((concept) => <span key={concept}>{concept}</span>)}</div></div></article>)}</div></div></section>
    <section className="bg-white py-12"><div className="container grid gap-10 lg:grid-cols-[.75fr_1.25fr]"><div><p className="eyebrow">Approfondir</p><h2 className="mt-4 font-display text-5xl leading-[.96] tracking-[-.055em]">Relier le contexte africain aux notions étudiées.</h2><p className="mt-5 max-w-md leading-7 text-[#61746E]">Commencez avec des concepts, puis observez comment les chaînes de valeur, l’emploi, les services ou les outils numériques se présentent dans un contexte précis.</p><Link href="/glossaire" className="mt-7 inline-flex items-center gap-2 text-sm font-semibold text-[#0E6356]">Ouvrir le glossaire <ArrowRight size={16} /></Link></div><div className="africa-learning-path"><div><BookOpenText size={19} /><span><small>01 · Concept</small><b>Comprendre une notion et ses limites.</b></span></div><div><ShieldCheck size={19} /><span><small>02 · Source</small><b>Vérifier l’indicateur, la période et la méthode.</b></span></div><div><Map size={19} /><span><small>03 · Contexte</small><b>Relier les données à un territoire et à des acteurs.</b></span></div></div></div></section>
    <section className="bg-[#123139] py-12 text-white"><div className="container"><div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="eyebrow text-[#9FD5B9]">Sources de départ</p><h2 className="mt-3 font-display text-4xl tracking-[-.05em]">Consulter des portails institutionnels.</h2></div><p className="max-w-md text-sm leading-6 text-[#C4D7CD]">Avant de citer une donnée, retrouvez l’indicateur exact et lisez sa fiche méthodologique.</p></div><div className="mt-7 grid gap-3 md:grid-cols-3">{resourceLinks.slice(-3).map((resource) => <a className="source-link" href={resource.url} target="_blank" rel="noreferrer" key={resource.title}><span>{resource.title}</span><ExternalLink size={16} /></a>)}</div></div></section>
  </SiteShell>;
}
