/**
 * Design: Atlas académique vivant — le répertoire est organisé en chapitres et repères de parcours, jamais comme un classement ou un catalogue neutre.
 */
import { useMemo, useState } from "react";
import { Link } from "wouter";
import { ArrowRight, BriefcaseBusiness, CircleAlert, Compass, Database, MapPinned, Search, Sigma, SlidersHorizontal, Scale, Wrench } from "lucide-react";
import SiteShell from "@/components/SiteShell";
import PageHero from "@/components/PageHero";
import AtlasTrail from "@/components/AtlasTrail";
import FavoriteButton from "@/components/FavoriteButton";
import { careerDirectory, careerFamilies, type CareerProfile } from "@/data/careersV4";

const levels = ["Tous niveaux", "Fondations", "Intermédiaire", "Approfondi"];

function CareerCard({ career, leading = false }: { career: CareerProfile; leading?: boolean }) {
  return <article className={`career-card career-card-v4 ${leading ? "career-card-leading" : "career-card-stop"}`}><FavoriteButton compact item={{ id: `career:${career.slug}`, type: "career", title: career.title, href: `/metiers/${career.slug}` }} /><Link href={`/metiers/${career.slug}`} className="career-card-link"><div className="flex items-center justify-between"><span className="career-category"><BriefcaseBusiness size={14} /> {career.category}</span><ArrowRight size={18} className={leading ? "text-[#C5E8D3]" : "text-[#0E6356]"} /></div><p className="career-stop-label">{leading ? "Piste d’entrée" : "Piste à comparer"}</p><h3>{career.title}</h3><p>{career.role}</p><div className="career-v4-meta"><span><Sigma size={13} /> {career.mathLevel}</span>{career.dataFocus && <span><Database size={13} /> Données</span>}{career.fieldFocus && <span><MapPinned size={13} /> Terrain</span>}</div><div className="mt-4 flex flex-wrap gap-2">{career.skills.slice(0, 2).map((skill) => <span className="skill-mini" key={skill}>{skill}</span>)}</div></Link></article>;
}

export default function Careers() {
  const [category, setCategory] = useState("Tous");
  const [query, setQuery] = useState("");
  const [mathLevel, setMathLevel] = useState("Tous niveaux");
  const [dataOnly, setDataOnly] = useState(false);
  const [fieldOnly, setFieldOnly] = useState(false);
  const displayed = useMemo(() => { const term = query.trim().toLowerCase(); return careerDirectory.filter((career) => { const searchable = [career.title, career.role, career.category, career.family, ...career.skills, ...career.tools, ...career.workTypes].join(" ").toLowerCase(); return (category === "Tous" || career.category === category) && (mathLevel === "Tous niveaux" || career.mathLevel === mathLevel) && (!dataOnly || career.dataFocus) && (!fieldOnly || career.fieldFocus) && (!term || searchable.includes(term)); }); }, [category, dataOnly, fieldOnly, mathLevel, query]);
  const grouped = useMemo(() => { if (category !== "Tous") return [[category, displayed] as const]; return careerFamilies.filter((family) => family !== "Tous").map((family) => [family, displayed.filter((item) => item.category === family)] as const).filter(([, items]) => items.length); }, [category, displayed]);
  const reset = () => { setCategory("Tous"); setMathLevel("Tous niveaux"); setDataOnly(false); setFieldOnly(false); setQuery(""); };

  return <SiteShell>
    <PageHero eyebrow="Répertoire des métiers liés à l’économie" title={<>Explorer plus loin,<br /><em>comparer avec méthode.</em></>} description="Ce répertoire est appelé à s’enrichir progressivement. Il présente des rôles, compétences et environnements possibles ; il ne prédit ni recrutement, ni débouché automatique." aside={<div className="career-hero-note"><Compass size={22} /><b>{careerDirectory.length} pistes à explorer</b><span>Filtrez par domaine, données, terrain et niveau de mathématiques pour ouvrir des directions, pas un verdict.</span></div>} />
    <AtlasTrail label="Du répertoire à un parcours vérifiable" steps={[{ label: "Domaine", note: "repérer" }, { label: "Métier", href: "/metiers", note: "explorer" }, { label: "Compétences", href: "/marche-competences", note: "développer" }, { label: "Formation", href: "/formations", note: "vérifier" }, { label: "Portail", href: "/opportunites", note: "consulter" }]} />
    <section className="bg-white py-7"><div className="container career-v4-controls"><label className="career-search"><Search size={18} /><span className="sr-only">Rechercher un métier</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Rechercher un métier, outil ou compétence…" /></label><Link href="/metiers/comparer" className="compare-link"><Scale size={16} /> Comparer des métiers</Link></div><div className="container career-filter-zone"><div className="flex gap-2 overflow-x-auto pb-1">{careerFamilies.map((item) => <button type="button" onClick={() => setCategory(item)} className={`filter-pill ${category === item ? "filter-pill-active" : ""}`} key={item}>{item}</button>)}</div><div className="career-toggle-row"><span><SlidersHorizontal size={15} /> Affiner</span>{levels.map((item) => <button type="button" className={mathLevel === item ? "career-toggle-active" : ""} onClick={() => setMathLevel(item)} key={item}><Sigma size={13} /> {item}</button>)}<button type="button" className={dataOnly ? "career-toggle-active" : ""} onClick={() => setDataOnly((value) => !value)}><Database size={13} /> Avec les données</button><button type="button" className={fieldOnly ? "career-toggle-active" : ""} onClick={() => setFieldOnly((value) => !value)}><MapPinned size={13} /> Avec le terrain</button></div></div></section>
    <section className="bg-[#F8F5ED] py-12 lg:py-16"><div className="container career-directory-layout"><aside className="career-directory-margin"><div><Compass size={19} /><p className="eyebrow">Marge de lecture</p><h2>Un métier se lit à travers ses contextes.</h2><p>Les intitulés changent d’une organisation à l’autre. Utilisez les chapitres pour comparer des pratiques, puis vérifiez formations, outils et opportunités à la source.</p></div><div className="career-margin-stat"><b>{displayed.length}</b><span>repères visibles</span></div><div className="career-terrain-note"><MapPinned size={16} /><p><b>Repère Togo & Afrique</b><br />Les environnements, études et accès à l’emploi dépendent des institutions, territoires et conditions locales : vérifiez avant d’agir.</p></div><Link href="/orientation">Relier à mon profil <ArrowRight size={16} /></Link></aside><main className="career-directory-main"><div className="career-directory-heading"><div><p className="eyebrow">{category === "Tous" ? "Cartographie par domaines" : category}</p><h2>{displayed.length} métier{displayed.length !== 1 ? "s" : ""} à explorer</h2></div><p>Les rôles et appellations varient selon les organisations. Les chapitres servent à passer du nom d’un métier aux compétences, formations, projets et sources pertinentes.</p></div>{displayed.length ? grouped.map(([family, items], chapterIndex) => <section className="career-chapter career-route-chapter" key={family}><header><span><Compass size={14} /> 0{chapterIndex + 1}</span><div><p className="eyebrow">Étape de cartographie</p><h3>{family}</h3></div><small>{items.length} piste{items.length !== 1 ? "s" : ""}</small></header><div className="career-chapter-route"><p><b>Prochaine lecture :</b> reliez une piste aux compétences, à une formation puis à une expérience concrète.</p><div><Link href="/marche-competences">Compétences <ArrowRight size={14} /></Link><Link href="/formations">Formations <ArrowRight size={14} /></Link><Link href="/projets">Projets <ArrowRight size={14} /></Link></div></div><div className="career-card-route-grid">{items.map((career, itemIndex) => <CareerCard key={career.slug} career={career} leading={itemIndex === 0} />)}</div></section>) : <div className="empty-state"><Search size={28} /><h2>Aucun métier ne correspond à ces filtres.</h2><p>Essayez de retirer un critère ou d’employer un mot-clé plus général.</p><button className="cta-primary" type="button" onClick={reset}>Réinitialiser les filtres</button></div>}</main></div></section>
    <section className="bg-[#EAF1E9] py-10"><div className="container flex flex-col gap-5 md:flex-row md:items-start"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-2xl bg-white text-[#0E6356]"><CircleAlert size={22} /></span><div><h2 className="font-display text-3xl tracking-[-.045em]">Ce qu’il faut garder en tête</h2><p className="mt-2 max-w-4xl leading-7 text-[#566A67]">Les débouchés ne sont jamais automatiques. Ils dépendent notamment du niveau d’études, de la spécialisation, des compétences, des expériences mobilisables et des réalités du marché du travail. EcoCompass aide à explorer et à préparer des prochaines étapes, sans garantir un résultat.</p></div><Link href="/orientation" className="shrink-0 cta-secondary"><Wrench size={17} /> Identifier mes pistes</Link></div></section>
  </SiteShell>;
}
