/** Design: Atlas académique vivant — l’étude de cas privilégie l’observation, l’hypothèse et les limites avant une explication. */
import { useState } from "react";
import { ArrowRight, Brain, ChevronRight, Eye, Lightbulb, ListChecks } from "lucide-react";
import { Link } from "wouter";
import SiteShell from "@/components/SiteShell";
import PageHero from "@/components/PageHero";
import AtlasTrail from "@/components/AtlasTrail";

const cases = [
  { id: "mais", title: "Pourquoi les prix du maïs augmentent-ils ?", theme: "Prix agricoles", context: "Des ménages et commerçants constatent des prix plus élevés sur plusieurs marchés.", data: "Prix relevés, période, quantités disponibles, coûts de transport, zones concernées et qualité de la collecte.", question: "Quelle démarche aide le mieux à comprendre cette hausse ?", choices: ["Choisir immédiatement une cause unique", "Comparer disponibilité, transport, saison et demande avant de conclure", "Utiliser un prix isolé comme preuve générale"], answer: 1, analysis: "Plusieurs mécanismes peuvent agir simultanément. Il faut comparer les lieux, les périodes et les conditions de collecte avant d’interpréter une variation.", notions: ["Offre", "Demande", "Inflation", "Chaîne de valeur"] },
  { id: "emploi", title: "Pourquoi le chômage des jeunes est-il un problème économique ?", theme: "Emploi", context: "De jeunes diplômés cherchent une première expérience alors que les organisations demandent parfois des compétences déjà pratiquées.", data: "Parcours de formation, durée de recherche, secteurs, stages, offres, compétences demandées et territoires.", question: "Quelle information est la plus utile à ajouter ?", choices: ["Distinguer emploi, chômage, sous-emploi et inactivité", "Supposer que tous les jeunes ont la même situation", "Regarder uniquement le nombre de diplômés"], answer: 0, analysis: "La situation exige des définitions précises et une lecture des parcours. Une difficulté d’accès au premier emploi peut mêler expérience, information, mobilité et évolution des besoins.", notions: ["Emploi", "Compétences", "Information", "Territoire"] },
  { id: "taux", title: "Comment une hausse des taux d’intérêt peut-elle influencer l’économie ?", theme: "Finance", context: "Une banque ajuste le coût du crédit dans un contexte où les prix et les anticipations évoluent.", data: "Taux, durée, type de crédit, inflation, revenu, investissement et échéances.", question: "Quelle formulation est la plus prudente ?", choices: ["Une hausse produit toujours le même effet", "Les effets dépendent des ménages, entreprises, crédits et délais", "Le taux seul suffit à expliquer l’investissement"], answer: 1, analysis: "Un taux agit dans un ensemble : durée du financement, risque, revenu, anticipation de la demande et autres coûts. L’effet peut varier selon les agents concernés.", notions: ["Taux d’intérêt", "Crédit", "Investissement", "Inflation"] },
  { id: "export", title: "Pourquoi augmenter les exportations ?", theme: "Commerce", context: "Un territoire cherche de nouveaux débouchés pour certains produits et services.", data: "Volumes, prix, coûts logistiques, normes, délais, partenaires, valeur ajoutée et emploi.", question: "Quelle question enrichit réellement l’analyse ?", choices: ["Quel produit est exporté et avec quelle valeur ajoutée locale ?", "Les exportations sont toujours positives sans condition", "Un seul pays suffit pour comparer tous les contextes"], answer: 0, analysis: "Les exportations peuvent ouvrir des débouchés, mais leur lecture dépend des produits, des coûts, des règles et de la valeur qui reste dans le territoire.", notions: ["Commerce", "Valeur ajoutée", "Logistique", "Compétitivité"] },
  { id: "investissement", title: "Comment un investissement peut-il contribuer à la croissance ?", theme: "Investissement", context: "Une organisation envisage un équipement ou une formation pour développer son activité.", data: "Coût initial, maintenance, financement, compétences, capacité utilisée, recettes attendues et risques.", question: "Quelle étape précède une conclusion ?", choices: ["Comparer des scénarios et expliciter les hypothèses", "Additionner les coûts sans regarder les usages", "Conclure avant de connaître le financement"], answer: 0, analysis: "Un investissement peut soutenir une capacité productive, mais les effets dépendent de son usage, des compétences, de la demande, du financement et du temps.", notions: ["Investissement", "Productivité", "Financement", "Risque"] },
  { id: "pauvrete", title: "Pourquoi la pauvreté ne se résume-t-elle pas au revenu ?", theme: "Développement", context: "Des ménages peuvent rencontrer plusieurs formes de privation malgré des situations monétaires différentes.", data: "Revenus, dépenses, accès à l’eau, santé, éducation, logement, emploi, localisation et sécurité.", question: "Quelle lecture évite de réduire la situation à un seul chiffre ?", choices: ["Observer plusieurs dimensions et préciser les seuils utilisés", "Utiliser un revenu sans contexte", "Comparer des ménages sans définir la période"], answer: 0, analysis: "Le revenu est utile mais ne résume pas l’accès effectif aux services, aux opportunités et à la sécurité. La démarche doit préciser les indicateurs et leurs limites.", notions: ["Pauvreté", "Inégalités", "Services", "Indicateurs"] },
];

export default function CaseStudies() {
  const [selected, setSelected] = useState(cases[0].id);
  const [answer, setAnswer] = useState<number | null>(null);
  const [revealed, setRevealed] = useState(false);
  const current = cases.find((item) => item.id === selected) || cases[0];
  return <SiteShell><PageHero variant="page-hero-cases" eyebrow="Études de cas · mode apprenant" title={<>Raisonner avant<br /><em>de chercher une réponse.</em></>} description="Chaque cas vous invite à décrire un problème, demander les informations utiles et comparer des explications. La réponse apparaît seulement après votre première hypothèse." aside={<div className="cases-hero-note"><Brain size={22} /><b>{cases.length} situations à explorer</b><span>Une démarche : problème → contexte → données → questions → analyse → conclusion.</span></div>} /><AtlasTrail label="Chemin d’une étude de cas" tone="night" steps={[{ label: "Problème", note: "décrire" }, { label: "Contexte", note: "situer" }, { label: "Données", href: "/ecolab", note: "chercher" }, { label: "Hypothèse", note: "comparer" }, { label: "Conclusion", note: "nuancer" }]} /><section className="bg-[#F8F5ED] py-10 lg:py-14"><div className="container case-layout"><aside className="case-index"><p className="eyebrow">Choisir un cas</p>{cases.map((item, index) => <button key={item.id} type="button" className={selected === item.id ? "case-index-active" : ""} onClick={() => { setSelected(item.id); setAnswer(null); setRevealed(false); }}><span>0{index + 1}</span><b>{item.title}</b><small>{item.theme}</small></button>)}</aside><main className="case-work"><div className="case-title"><div><p className="eyebrow">{current.theme}</p><h1>{current.title}</h1></div><Eye size={20} /></div><div className="case-flow"><article><span>01</span><b>Problème</b><p>{current.context}</p></article><article><span>02</span><b>Données à rechercher</b><p>{current.data}</p></article></div><div className="case-question"><p className="eyebrow">Votre première lecture</p><h2>{current.question}</h2>{current.choices.map((choice, index) => <button key={choice} className={answer === index ? (index === current.answer ? "case-answer-good" : "case-answer-selected") : ""} type="button" onClick={() => { setAnswer(index); setRevealed(false); }}><span>{String.fromCharCode(65 + index)}</span>{choice}</button>)}{answer !== null && <button type="button" className="case-reveal" onClick={() => setRevealed(true)}>Voir l’explication <Lightbulb size={16} /></button>}{revealed && <div className="case-explanation"><Lightbulb size={17} /><p>{current.analysis}</p></div>}</div><div className="case-takeaways"><div><ListChecks size={18} /><p><b>Conclusion à retenir</b><br />Une bonne analyse distingue l’observation, les explications possibles et les informations manquantes.</p></div><div><p className="eyebrow">Notions à relier</p>{current.notions.map((item) => <span key={item}>{item}</span>)}</div></div><Link href="/ecolab" className="case-next">Tester une lecture de données dans EcoLab <ArrowRight size={17} /></Link></main></div></section></SiteShell>;
}
