/**
 * Design: Atlas académique vivant — un parcours en sept jalons, guidé et sans surcharge de texte.
 */
import { useState } from "react";
import { Link } from "wouter";
import { ArrowLeft, ArrowRight, BookOpenText, BriefcaseBusiness, Check, Lightbulb, MapPinned } from "lucide-react";
import SiteShell from "@/components/SiteShell";
import { discoverSteps } from "@/data/ecocompass";

export default function Discover() {
  const [active, setActive] = useState(0);
  const step = discoverSteps[active];
  const isLast = active === discoverSteps.length - 1;
  const progress = ((active + 1) / discoverSteps.length) * 100;
  return <SiteShell>
    <section className="discover-hero"><div className="container grid gap-8 lg:grid-cols-[1fr_.85fr]"><div><p className="eyebrow">Parcours guidé · 20 à 30 minutes</p><h1>Découvrir l’économie,<br /><em>par étapes.</em></h1><p>Un chemin clair pour relier les premières notions à des situations proches de vous. Avancez à votre rythme, reprenez quand vous le souhaitez.</p></div><div className="discover-art"><img src="/manus-storage/ecocompass-discover-path_83fca56b.jpg" alt="Illustration d’un chemin de découverte économique en sept stations" /></div></div></section>
    <section className="bg-white py-8"><div className="container"><div className="mb-4 flex items-center justify-between gap-4"><p className="eyebrow">Étape {String(active + 1).padStart(2, "0")} / 07</p><span className="font-mono text-xs text-[#607271]">{Math.round(progress)} % du parcours</span></div><div className="h-1.5 overflow-hidden rounded-full bg-[#E6EEE9]"><div className="h-full rounded-full bg-[#0E6356] transition-all duration-300" style={{ width: `${progress}%` }} /></div><div className="mt-6 flex gap-2 overflow-x-auto pb-1">{discoverSteps.map((item, index) => <button type="button" key={item.title} onClick={() => setActive(index)} className={`step-dot ${index === active ? "step-dot-active" : ""} ${index < active ? "step-dot-done" : ""}`} aria-label={`Aller à l’étape ${index + 1} : ${item.title}`}><span>{index < active ? <Check size={14} /> : String(index + 1).padStart(2, "0")}</span><b>{item.title}</b></button>)}</div></div></section>
    <section className="bg-[#F8F5ED] py-12 lg:py-20"><div className="container grid gap-10 lg:grid-cols-[180px_1fr_260px]"><aside className="hidden lg:block"><p className="font-mono text-sm text-[#71827D]">{step.eyebrow}</p><div className="mt-4 text-7xl font-display tracking-[-.09em] text-[#BBD3C6]">0{active + 1}</div></aside><article className="discover-card"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-[#DDEDE6] text-[#0E6356]"><Lightbulb size={20} /></span><p className="eyebrow">{step.eyebrow}</p></div><h2>{step.title}</h2><p className="discover-main-text">{step.text}</p><div className="example-callout"><span>Exemple concret</span><p>{step.example}</p></div><div className="mt-8 flex flex-wrap items-center justify-between gap-3"><button type="button" onClick={() => setActive((value) => Math.max(0, value - 1))} disabled={active === 0} className="nav-back"><ArrowLeft size={17} /> Précédent</button>{!isLast ? <button type="button" onClick={() => setActive((value) => Math.min(discoverSteps.length - 1, value + 1))} className="cta-primary">Étape suivante <ArrowRight size={18} /></button> : <span className="inline-flex items-center gap-2 rounded-full bg-[#DDEDE6] px-4 py-2.5 text-sm font-semibold text-[#0E6356]"><Check size={17} /> Parcours terminé</span>}</div></article><aside className="discover-aside"><p className="eyebrow">À ce stade</p><h3>Gardez l’idée essentielle.</h3><p>Il ne s’agit pas de mémoriser tout de suite, mais de relier une notion à une situation et à une question.</p><div className="mt-6 h-px bg-[#14333A]/10" /><p className="mt-5 font-mono text-xs leading-5 text-[#64736E]">Repère : vous pourrez retrouver cette notion dans les cours et la recherche.</p></aside></div></section>
    {isLast && <section className="bg-[#123139] py-14 text-white"><div className="container"><p className="eyebrow text-[#95CDB6]">Et maintenant ?</p><h2 className="mt-4 max-w-2xl font-display text-5xl leading-[.98] tracking-[-.055em]">Choisissez une prochaine direction, sans devoir choisir votre vie entière.</h2><div className="mt-8 grid gap-3 md:grid-cols-3"><Link href="/apprendre" className="next-route"><BookOpenText /><span><b>Apprendre</b><small>Commencer les fondamentaux</small></span><ArrowRight /></Link><Link href="/metiers" className="next-route"><BriefcaseBusiness /><span><b>Métiers</b><small>Explorer des rôles et compétences</small></span><ArrowRight /></Link><Link href="/togo" className="next-route"><MapPinned /><span><b>Économie du Togo</b><small>Relier notions et contexte</small></span><ArrowRight /></Link></div></div></section>}
  </SiteShell>;
}
