/**
 * Design: Atlas académique vivant — l’explication est une bibliothèque pédagogique préparée, jamais une fausse conversation avec une IA.
 */
import { useState } from "react";
import { ArrowRight, BookOpenText, CircleAlert, GraduationCap, Lightbulb, Sparkles } from "lucide-react";
import { Link } from "wouter";
import SiteShell from "@/components/SiteShell";
import PageHero from "@/components/PageHero";
import AtlasTrail from "@/components/AtlasTrail";

const topics = {
  PIB: { debutant: "Le PIB est une manière de compter la valeur des biens et services produits sur un territoire pendant une période. Il aide à observer l’activité, mais ne dit pas tout du bien-être.", etudiant: "Le produit intérieur brut mesure la valeur ajoutée produite dans l’économie. Sa lecture suppose d’indiquer prix courants ou constants, période, population et limites de l’indicateur.", avance: "L’analyse du PIB distingue production, dépense et revenu. Pour comparer des évolutions, il faut notamment interroger le déflateur, le PIB réel, le PIB par habitant, les révisions de série et les activités non observées." },
  Inflation: { debutant: "L’inflation décrit une hausse générale des prix. Si les revenus n’augmentent pas au même rythme, le pouvoir d’achat peut diminuer.", etudiant: "L’inflation est généralement étudiée à partir d’un indice de prix. Il faut préciser le panier, la période et les groupes de produits avant d’interpréter une variation.", avance: "L’analyse sépare chocs d’offre, demande, anticipations, taux de change et politique monétaire. Une série agrégée doit être complétée par des contributions sectorielles et une méthode de calcul." },
  Chômage: { debutant: "Le chômage concerne des personnes sans emploi qui cherchent à travailler. Son taux donne un repère, mais ne décrit pas à lui seul toutes les difficultés d’accès au travail.", etudiant: "Le taux de chômage dépend des définitions de l’emploi, de la recherche active et de la population de référence. Il doit être lu avec le sous-emploi, l’informalité et la participation.", avance: "L’interprétation combine structure démographique, qualifications, cycle économique, institutions du marché du travail et sources d’enquête. Les comparaisons internationales requièrent une attention méthodologique." },
  "Dette publique": { debutant: "La dette publique correspond aux emprunts d’un État. Elle peut financer des projets, mais elle implique aussi des remboursements et des intérêts.", etudiant: "La dette se lit avec son montant, son rapport à l’activité économique, sa monnaie, son échéance et son coût. Aucun seuil isolé ne suffit à conclure.", avance: "L’analyse de soutenabilité associe dynamique de croissance, taux d’intérêt, solde primaire, risques de change, profil d’échéances et capacité de mobilisation des recettes." }
} as const;
type Topic = keyof typeof topics;
type Level = keyof typeof topics[Topic];

export default function ExplainEconomy() {
  const [topic, setTopic] = useState<Topic>("PIB");
  const [level, setLevel] = useState<Level>("debutant");
  return <SiteShell>
    <PageHero variant="page-hero-learn" eyebrow="Bibliothèque d’explications préparées" title={<>Explique-moi,<br /><em>à mon niveau.</em></>} description="Choisissez une notion et un niveau de lecture. Cette bibliothèque propose des explications préparées pour vous aider à avancer, puis à poser de meilleures questions devant une source ou un cours." aside={<div className="course-hero-note"><BookOpenText size={22} /><b>Une notion, trois niveaux</b><span>Débutant, étudiant et avancé : adaptez la profondeur sans perdre les repères de méthode.</span></div>} />
    <AtlasTrail label="Notion → niveau → application" steps={[{ label: "Notion", href: "/glossaire", note: "choisir" }, { label: "Niveau", href: "/expliquer", note: "adapter" }, { label: "Cours", href: "/apprendre", note: "approfondir" }, { label: "EcoLab", href: "/ecolab", note: "observer" }, { label: "Défi", href: "/defis", note: "raisonner" }]} />
    <section className="bg-[#F8F5ED] py-12"><div className="container explain-layout"><aside><p className="eyebrow">Choisir une notion</p>{(Object.keys(topics) as Topic[]).map((item) => <button type="button" className={topic === item ? "explain-topic-active" : ""} onClick={() => setTopic(item)} key={item}>{item}</button>)}<div><CircleAlert size={16} /><p>Pour une valeur, une date ou une politique précise, consultez une source institutionnelle et contextualisée.</p></div></aside><main><div className="explain-levels"><p className="eyebrow">Choisir un niveau</p><div>{(["debutant", "etudiant", "avance"] as Level[]).map((item) => <button type="button" className={level === item ? "explain-level-active" : ""} onClick={() => setLevel(item)} key={item}>{item === "debutant" ? "Débutant" : item === "etudiant" ? "Étudiant" : "Avancé"}</button>)}</div></div><article><span>{topic}</span><h1>{topic}, expliqué au niveau {level === "debutant" ? "débutant" : level === "etudiant" ? "étudiant" : "avancé"}.</h1><p>{topics[topic][level]}</p><div className="explain-questions"><Lightbulb size={18} /><div><b>Question à emporter</b><p>Quelle unité, quelle période, quelle source et quelle limite faudrait-il préciser avant d’utiliser cette notion dans une analyse ?</p></div></div><div className="explain-next"><Link href="/glossaire">Voir les notions liées <ArrowRight size={16} /></Link><Link href="/ecolab">Observer une série de démonstration <ArrowRight size={16} /></Link></div></article><div className="explain-prepared"><Sparkles size={18} /><p><b>Repère de lecture.</b> Cette explication donne une première base. Pour une question située, comparez plusieurs sources, notez ce qui manque et demandez conseil à un enseignant ou à un professionnel compétent.</p></div></main></div></section>
  </SiteShell>;
}
