/** Design: Atlas académique vivant — guide d’établissements avec source, date et lien officiel visibles. */
import { useMemo, useState } from "react";
import { ArrowUpRight, Building2, CalendarCheck2, MapPin, Search, ShieldCheck } from "lucide-react";
import SiteShell from "@/components/SiteShell";
import PageHero from "@/components/PageHero";
import AtlasTrail from "@/components/AtlasTrail";
import { institutions } from "@/data/ecosystemV4";

export default function Institutions() {
  const [query, setQuery] = useState(""); const [scope, setScope] = useState("Tous");
  const list = useMemo(() => { const term = query.toLowerCase().trim(); return institutions.filter((item) => (scope === "Tous" || item.scope === scope) && (!term || [item.name, item.city, ...item.specialties, ...item.levels].join(" ").toLowerCase().includes(term))); }, [query, scope]);
  return <SiteShell><PageHero variant="page-hero-institutions" eyebrow="Guide des établissements · sources visibles" title={<>Chercher une formation,<br /><em>vérifier à la source.</em></>} description="Ce guide répertorie progressivement des établissements et leurs pages officielles. Il ne remplace pas les informations d’admission : chaque détail doit être vérifié directement auprès de l’établissement." aside={<div className="institution-hero-note"><ShieldCheck size={22} /><b>Sources officielles prioritaires</b><span>Nom, pays, date de consultation et lien officiel restent visibles à côté de chaque repère.</span></div>} /><AtlasTrail label="De l’exploration à la vérification" steps={[{ label: "Formation", href: "/formations", note: "repérer" }, { label: "Établissement", href: "/etablissements", note: "identifier" }, { label: "Source", note: "vérifier" }, { label: "Compétences", href: "/marche-competences", note: "relier" }, { label: "Métiers", href: "/metiers", note: "explorer" }]} />
    <section className="bg-[#F8F5ED] py-10 lg:py-14"><div className="container"><div className="institution-filter"><label><Search size={18} /><span className="sr-only">Rechercher un établissement</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Rechercher un établissement, une ville ou une spécialité…" /></label><div>{["Tous", "Togo", "Afrique", "International"].map((item) => <button type="button" key={item} className={scope === item ? "filter-pill filter-pill-active" : "filter-pill"} onClick={() => setScope(item)}>{item}</button>)}</div></div><div className="institution-warning"><CalendarCheck2 size={18} /><p><b>Information à vérifier :</b> les admissions, frais, calendriers, programmes et disponibilités peuvent changer. EcoCompass conserve le lien officiel afin de faciliter votre vérification.</p></div><div className="institution-grid">{list.map((item) => <article key={item.id}><header><span><MapPin size={13} /> {item.city}, {item.country}</span><b>{item.scope}</b></header><h2>{item.name}</h2><p>{item.description}</p><div className="institution-specialties">{item.specialties.slice(0, 5).map((specialty) => <span key={specialty}>{specialty}</span>)}</div><footer><div><small>Source officielle</small><b>{item.sourceLabel}</b><small>Consultée le {item.checkedAt}</small></div><a href={item.officialUrl} target="_blank" rel="noreferrer">Ouvrir la source <ArrowUpRight size={15} /></a></footer><p className="institution-note">{item.admissionNote}</p></article>)}</div></div></section></SiteShell>;
}
