/**
 * Design: Atlas académique vivant — le tableau de bord traduit une progression pédagogique locale, jamais une certification.
 */
import { useMemo, useState } from "react";
import { ArrowRight, Award, BarChart3, BookOpenCheck, BookmarkCheck, CheckCircle2, Compass, FolderKanban, PencilLine, Sparkles, Target } from "lucide-react";
import { Link } from "wouter";
import SiteShell from "@/components/SiteShell";
import PageHero from "@/components/PageHero";
import AtlasTrail from "@/components/AtlasTrail";
import { useLearning } from "@/contexts/LearningContext";
import { courses } from "@/data/ecocompass";
import { courseSkills, guidedProjects, learningPaths, skillDefinitions } from "@/data/v3";

const interests = ["Données", "Finance", "Développement", "Macroéconomie", "Métiers", "Fondamentaux"];

export default function MyCompass() {
  const { profile, updateProfile, completed, started, quizScores, favorites, lastCourse, projects, activePath, setActivePath } = useLearning();
  const [editing, setEditing] = useState(!profile.name);
  const [draft, setDraft] = useState(profile);
  const lastCourseItem = courses.find((course) => course.slug === lastCourse) || courses[0];
  const average = useMemo(() => { const scores = Object.values(quizScores); return scores.length ? Math.round(scores.reduce((sum, item) => sum + (item.score / item.total) * 100, 0) / scores.length) : null; }, [quizScores]);
  const activeLearningPath = learningPaths.find((path) => path.slug === activePath);
  const suggestedPaths = useMemo(() => [...learningPaths].sort((a, b) => Number(profile.interests.includes(b.interest)) - Number(profile.interests.includes(a.interest))).slice(0, 3), [profile.interests]);
  const skills = skillDefinitions.map((skill) => { const fromCourses = completed.filter((slug) => courseSkills[slug]?.includes(skill.id)).length * 18; const fromProjects = projects.filter((project) => guidedProjects.find((item) => item.slug === project.templateSlug)?.skills.some((item) => item.toLowerCase().includes(skill.label.toLowerCase().split(" ")[0])))?.length * 14; return { ...skill, progress: Math.min(100, fromCourses + fromProjects) }; });
  const toggleInterest = (interest: string) => setDraft((current) => ({ ...current, interests: current.interests.includes(interest) ? current.interests.filter((item) => item !== interest) : [...current.interests, interest] }));
  const saveProfile = () => { updateProfile(draft); setEditing(false); };
  return <SiteShell>
    <PageHero variant="page-hero-compass" eyebrow="Espace personnel local" title={<>Mon <em>EcoCompass</em><br />en pratique.</>} description="Retrouvez votre progression, vos repères et des suggestions pour avancer. Ces informations restent enregistrées localement dans ce navigateur ; elles ne constituent pas une évaluation ni une certification." aside={<div className="compass-hero-note"><Compass size={22} /><b>{profile.name ? `Bonjour, ${profile.name}` : "Votre espace de pratique"}</b><span>Votre parcours se construit avec vos choix, vos cours, vos essais et vos projets.</span></div>} />
    <AtlasTrail label="De votre profil à votre pratique" steps={[{ label: "Profil", href: "/mon-ecocompass", note: "vos intérêts" }, { label: "Cours", href: "/apprendre", note: "vos repères" }, { label: "EcoLab", href: "/ecolab", note: "vos observations" }, { label: "Projets", href: "/projets", note: "vos traces" }, { label: "Compétences", href: "/competences", note: "vos liens" }]} />
    <section className="bg-[#F8F5ED] py-10 lg:py-14"><div className="container"><div className="dashboard-topline"><div><p className="eyebrow">Mon parcours</p><h2>Avancer avec des repères clairs.</h2></div><button type="button" className="dashboard-edit" onClick={() => { setDraft(profile); setEditing((value) => !value); }}><PencilLine size={16} /> {editing ? "Fermer" : "Modifier mon profil"}</button></div>{editing && <form className="profile-form" onSubmit={(event) => { event.preventDefault(); saveProfile(); }}><label>Pseudonyme ou prénom <input value={draft.name} onChange={(event) => setDraft((current) => ({ ...current, name: event.target.value }))} placeholder="Par exemple : Afi" /></label><label>Niveau actuel <select value={draft.level} onChange={(event) => setDraft((current) => ({ ...current, level: event.target.value }))}><option>Je découvre l’économie</option><option>Terminale ou nouveau bachelier</option><option>L1 ou L2</option><option>Formation avancée</option><option>Jeune professionnel</option></select></label><label>Objectif actuel <input value={draft.goal} onChange={(event) => setDraft((current) => ({ ...current, goal: event.target.value }))} placeholder="Ex. apprendre à lire les données" /></label><fieldset><legend>Domaines qui vous intéressent</legend><div>{interests.map((interest) => <button type="button" className={`interest-toggle ${draft.interests.includes(interest) ? "interest-toggle-active" : ""}`} onClick={() => toggleInterest(interest)} key={interest}>{draft.interests.includes(interest) && <CheckCircle2 size={14} />}{interest}</button>)}</div></fieldset><button className="cta-primary" type="submit">Enregistrer mon profil <ArrowRight size={17} /></button></form>}
      <div className="dashboard-grid"><article className="dashboard-progress"><p className="eyebrow">Progression générale</p><div className="progress-ratio"><b>{Math.round((completed.length / courses.length) * 100)} %</b><span>{completed.length} / {courses.length} cours terminés</span></div><div className="dashboard-progress-bar"><i style={{ width: `${(completed.length / courses.length) * 100}%` }} /></div><Link href={`/apprendre/${lastCourseItem.slug}`} className="dashboard-continue"><BookOpenCheck size={18} /><span><small>Continuer mon apprentissage</small><b>{lastCourseItem.title}</b></span><ArrowRight size={17} /></Link></article><article className="dashboard-stat"><BookOpenCheck /><b>{started.length}</b><span>cours en cours</span></article><article className="dashboard-stat"><BarChart3 /><b>{Object.keys(quizScores).length}</b><span>quiz réalisés</span>{average !== null && <small>Moyenne locale : {average} %</small>}</article><article className="dashboard-stat"><FolderKanban /><b>{projects.length}</b><span>projets enregistrés</span></article><article className="dashboard-stat"><BookmarkCheck /><b>{favorites.length}</b><span>favoris</span></article></div></div></section>
    <section className="bg-white py-12 lg:py-16"><div className="container grid gap-10 lg:grid-cols-[.86fr_1.14fr]"><div><p className="eyebrow">Compétences en pratique</p><h2 className="mt-3 font-display text-5xl leading-[.96] tracking-[-.055em]">Vos repères de progression.</h2><p className="mt-5 max-w-md leading-7 text-[#62746F]">Ces barres indiquent seulement les contenus terminés et projets consignés dans EcoCompass. Elles ne mesurent pas une compétence professionnelle et ne remplacent pas un retour humain.</p><Link href="/competences" className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-[#0E6356]">Voir la carte complète <ArrowRight size={16} /></Link></div><div className="skill-preview">{skills.map((skill) => <div key={skill.id}><div><span>{skill.label}</span><small>{skill.progress} %</small></div><i><b style={{ width: `${skill.progress}%` }} /></i><p>{skill.description}</p></div>)}</div></div></section>
    <section className="bg-[#14333A] py-12 text-white"><div className="container"><div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="eyebrow text-[#9FD5B9]">Parcours suggérés</p><h2 className="mt-3 font-display text-5xl tracking-[-.055em]">Des itinéraires à adapter.</h2></div><p className="max-w-md text-sm leading-6 text-[#C4D7CD]">Les suggestions utilisent vos intérêts enregistrés et restent des propositions ; vous pouvez les modifier à tout moment.</p></div><div className="mt-8 grid gap-4 lg:grid-cols-3">{suggestedPaths.map((path) => <article className={`path-card ${activePath === path.slug ? "path-card-active" : ""}`} key={path.slug}><span>{path.level}</span><h3>{path.title}</h3><p>{path.objective}</p><div>{path.skills.map((skill) => <small key={skill}>{skill}</small>)}</div><footer><b>{path.duration} · {path.courseSlugs.length} cours</b><button type="button" onClick={() => setActivePath(path.slug)}>{activePath === path.slug ? "Parcours choisi" : "Choisir ce parcours"} <Target size={15} /></button></footer></article>)}</div>{activeLearningPath && <div className="active-path-note"><Award size={18} /><p><b>Parcours actif : {activeLearningPath.title}.</b> Retrouvez les cours associés et suivez leur progression dans votre espace personnel.</p><Link href="/apprendre">Ouvrir les cours <ArrowRight size={16} /></Link></div>}</div></section>
  </SiteShell>;
}
