/**
 * Design: Atlas académique vivant — le tableau de bord traduit des actions locales, des choix révisables et des repères de progression, sans notation artificielle.
 */
import { useMemo, useState } from "react";
import { ArrowRight, Award, BarChart3, BookOpenCheck, BookmarkCheck, CalendarDays, CheckCircle2, Circle, ClipboardList, Compass, FolderKanban, PencilLine, Plus, Target, Trash2 } from "lucide-react";
import { Link } from "wouter";
import SiteShell from "@/components/SiteShell";
import PageHero from "@/components/PageHero";
import AtlasTrail from "@/components/AtlasTrail";
import ActionProgressChart from "@/components/ActionProgressChart";
import { useLearning } from "@/contexts/LearningContext";
import { courses } from "@/data/ecocompass";
import { courseSkills, guidedProjects, learningPaths, skillDefinitions } from "@/data/v3";
import { goalPaths } from "@/data/v5";

const interests = ["Données", "Finance", "Développement", "Macroéconomie", "Métiers", "Fondamentaux"];
const timeframes = ["quotidien", "hebdomadaire", "mensuel", "long-terme"] as const;

export default function MyCompass() {
  const { profile, updateProfile, completed, started, quizScores, favorites, lastCourse, projects, activePath, setActivePath, goals, actionTasks, addGoal, toggleGoal, removeGoal, addTask, toggleTask, removeTask, badges } = useLearning();
  const [editing, setEditing] = useState(!profile.name);
  const [draft, setDraft] = useState(profile);
  const [goalDraft, setGoalDraft] = useState("");
  const [goalTimeframe, setGoalTimeframe] = useState<typeof timeframes[number]>("long-terme");
  const [taskDraft, setTaskDraft] = useState("");
  const [taskDueDate, setTaskDueDate] = useState("");
  const lastCourseItem = courses.find((course) => course.slug === lastCourse) || courses[0];
  const average = useMemo(() => { const scores = Object.values(quizScores); return scores.length ? Math.round(scores.reduce((sum, item) => sum + (item.score / item.total) * 100, 0) / scores.length) : null; }, [quizScores]);
  const activeLearningPath = learningPaths.find((path) => path.slug === activePath);
  const suggestedPaths = useMemo(() => [...learningPaths].sort((a, b) => Number(profile.interests.includes(b.interest)) - Number(profile.interests.includes(a.interest))).slice(0, 3), [profile.interests]);
  const skills = skillDefinitions.map((skill) => { const fromCourses = completed.filter((slug) => courseSkills[slug]?.includes(skill.id)).length * 18; const fromProjects = projects.filter((project) => guidedProjects.find((item) => item.slug === project.templateSlug)?.skills.some((item) => item.toLowerCase().includes(skill.label.toLowerCase().split(" ")[0])))?.length * 14; return { ...skill, progress: Math.min(100, fromCourses + fromProjects) }; });
  const overallProgress = Math.min(100, Math.round(((completed.length / Math.max(courses.length, 1)) * 60) + (Math.min(projects.length, 4) * 8) + (Math.min(actionTasks.filter((task) => task.completed).length, 6) * 4)));
  const goalPath = goalPaths.find((path) => profile.goal.toLowerCase().includes(path.label.toLowerCase().replace("Devenir ", "").replace("Explorer ", ""))) || goalPaths.find((path) => profile.interests.some((interest) => path.label.toLowerCase().includes(interest.toLowerCase())));
  const followedCareers = favorites.filter((item) => item.type === "career").length;
  const savedFormations = favorites.filter((item) => item.type === "formation").length;
  const savedOpportunities = favorites.filter((item) => item.type === "opportunity").length;
  const toggleInterest = (interest: string) => setDraft((current) => ({ ...current, interests: current.interests.includes(interest) ? current.interests.filter((item) => item !== interest) : [...current.interests, interest] }));
  const saveProfile = () => { updateProfile(draft); setEditing(false); };
  const createGoal = (event: React.FormEvent) => { event.preventDefault(); if (!goalDraft.trim()) return; addGoal({ title: goalDraft.trim(), timeframe: goalTimeframe }); setGoalDraft(""); };
  const createTask = (event: React.FormEvent) => { event.preventDefault(); if (!taskDraft.trim()) return; addTask({ title: taskDraft.trim(), dueDate: taskDueDate || undefined, source: "manual" }); setTaskDraft(""); setTaskDueDate(""); };
  return <SiteShell>
    <PageHero variant="page-hero-compass" eyebrow="Espace personnel local" title={<>Mon tableau de bord,<br /><em>à mon rythme.</em></>} description="Vos objectifs, actions et repères restent dans ce navigateur. Ils vous aident à organiser votre progression ; ils ne constituent ni une évaluation, ni une certification." aside={<div className="compass-hero-note"><Compass size={22} /><b>{profile.name ? `Bonjour, ${profile.name}` : "Votre espace de pratique"}</b><span>{profile.goal ? `Objectif actuel : ${profile.goal}` : "Définissez un objectif ou commencez par explorer des pistes."}</span></div>} />
    <AtlasTrail label="Du profil aux prochaines actions" steps={[{ label: "Profil", href: "/mon-ecocompass", note: "choisir" }, { label: "Objectif", href: "/mon-parcours", note: "relier" }, { label: "Cours", href: "/apprendre", note: "apprendre" }, { label: "Projet", href: "/projets", note: "pratiquer" }, { label: "Portfolio", href: "/portfolio", note: "préparer" }]} />
    <section className="bg-[#F8F5ED] py-10 lg:py-14"><div className="container"><div className="dashboard-topline"><div><p className="eyebrow">Mon accompagnement</p><h2>Des repères, puis des actions.</h2></div><button type="button" className="dashboard-edit" onClick={() => { setDraft(profile); setEditing((value) => !value); }}><PencilLine size={16} /> {editing ? "Fermer" : "Modifier mon profil"}</button></div>{editing && <form className="profile-form" onSubmit={(event) => { event.preventDefault(); saveProfile(); }}><label>Pseudonyme ou prénom <input value={draft.name} onChange={(event) => setDraft((current) => ({ ...current, name: event.target.value }))} placeholder="Par exemple : Afi" /></label><label>Niveau actuel <select value={draft.level} onChange={(event) => setDraft((current) => ({ ...current, level: event.target.value }))}><option>Je découvre l’économie</option><option>Terminale ou nouveau bachelier</option><option>L1 ou L2</option><option>Formation avancée</option><option>Jeune professionnel</option></select></label><label>Objectif professionnel <input value={draft.goal} onChange={(event) => setDraft((current) => ({ ...current, goal: event.target.value }))} placeholder="Ex. devenir analyste économique" /></label><label>Spécialisation éventuelle <input value={draft.specialization || ""} onChange={(event) => setDraft((current) => ({ ...current, specialization: event.target.value }))} placeholder="Ex. données, finance, développement" /></label><fieldset><legend>Domaines qui vous intéressent</legend><div>{interests.map((interest) => <button type="button" className={`interest-toggle ${draft.interests.includes(interest) ? "interest-toggle-active" : ""}`} onClick={() => toggleInterest(interest)} key={interest}>{draft.interests.includes(interest) && <CheckCircle2 size={14} />}{interest}</button>)}</div></fieldset><button className="cta-primary" type="submit">Enregistrer mon profil <ArrowRight size={17} /></button></form>}
      <div className="dashboard-grid dashboard-grid-v5"><article className="dashboard-progress"><p className="eyebrow">Progression générale</p><div className="progress-ratio"><b>{overallProgress} %</b><span>à partir de cours, projets et tâches réalisées</span></div><div className="dashboard-progress-bar"><i style={{ width: `${overallProgress}%` }} /></div><Link href={`/apprendre/${lastCourseItem.slug}`} className="dashboard-continue"><BookOpenCheck size={18} /><span><small>Prochaine trace d’apprentissage</small><b>{lastCourseItem.title}</b></span><ArrowRight size={17} /></Link></article><article className="dashboard-stat"><small>Jalon 01</small><BookOpenCheck /><b>{completed.length}</b><span>cours consolidés</span></article><article className="dashboard-stat"><small>Jalon 02</small><FolderKanban /><b>{projects.length}</b><span>traces de pratique</span></article><article className="dashboard-stat"><small>Jalon 03</small><BookmarkCheck /><b>{followedCareers + savedFormations + savedOpportunities}</b><span>pistes repérées</span></article><article className="dashboard-stat"><small>Jalon 04</small><Award /><b>{badges.length}</b><span>repères documentés</span>{average !== null && <small>Quiz local : {average} %</small>}</article></div><div className="dashboard-route-note"><Compass size={18} /><p><b>Lire votre carte :</b> un chiffre devient un jalon lorsque vous le reliez à une prochaine trace — un cours, une action, un projet ou une vérification.</p></div>{badges.length > 0 && <div className="dashboard-badges"><p className="eyebrow">Badges obtenus par des actions</p><div>{badges.map((badge) => <span key={badge}><Award size={14} /> {badge}</span>)}</div><small>Un badge apparaît après une action enregistrée, jamais après la simple ouverture d’une page.</small></div>}</div></section>
    <ActionProgressChart actionTasks={actionTasks} goals={goals} completedCourses={completed.length} totalCourses={courses.length} projectCount={projects.length} />
    <section className="bg-white py-12 lg:py-16"><div className="container dashboard-action-layout"><aside className="dashboard-objective-card"><p className="eyebrow">Mon objectif</p><Target size={22} /><h2>{profile.goal || "Je ne sais pas encore."}</h2><p>{profile.goal ? "Votre objectif reste modifiable. EcoCompass propose des repères généralement utiles, sans imposer une seule voie." : "Commencez par Découvrir ou Orientation : vous pourrez choisir un objectif plus tard."}</p>{goalPath ? <Link href="/mon-parcours">Voir le parcours proposé <ArrowRight size={16} /></Link> : <Link href="/orientation">Explorer mes pistes <ArrowRight size={16} /></Link>}</aside><div className="dashboard-actions"><div className="dashboard-actions-heading"><div><p className="eyebrow">Cette semaine</p><h2>Mon plan d’action.</h2></div><span>{actionTasks.filter((task) => task.completed).length} / {actionTasks.length} terminée{actionTasks.length > 1 ? "s" : ""}</span></div><form className="task-create" onSubmit={createTask}><input value={taskDraft} onChange={(event) => setTaskDraft(event.target.value)} placeholder="Ajouter une action concrète…" aria-label="Nouvelle action" /><input value={taskDueDate} onChange={(event) => setTaskDueDate(event.target.value)} type="date" aria-label="Échéance" /><button type="submit" aria-label="Ajouter l’action"><Plus size={18} /></button></form><div className="task-list">{actionTasks.length ? actionTasks.slice(0, 6).map((task) => <article className={task.completed ? "task-done" : ""} key={task.id}><button type="button" onClick={() => toggleTask(task.id)} aria-label={task.completed ? "Marquer comme à faire" : "Marquer comme terminé"}>{task.completed ? <CheckCircle2 size={18} /> : <Circle size={18} />}</button><div><b>{task.title}</b>{task.dueDate && <small><CalendarDays size={12} /> Échéance : {new Intl.DateTimeFormat("fr-FR", { day: "numeric", month: "short" }).format(new Date(`${task.dueDate}T12:00:00`))}</small>}</div><button className="task-delete" type="button" onClick={() => removeTask(task.id)} aria-label="Supprimer l’action"><Trash2 size={15} /></button></article>) : <div className="task-empty"><ClipboardList size={19} /><p>Ajoutez une première action courte et vérifiable pour faire avancer votre parcours.</p></div>}</div><Link href="/plan-action" className="dashboard-more-link">Ouvrir mon plan complet <ArrowRight size={16} /></Link></div></div></section>
    <section className="bg-[#14333A] py-12 text-white"><div className="container"><div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="eyebrow text-[#9FD5B9]">Parcours suggérés</p><h2 className="mt-3 font-display text-5xl tracking-[-.055em]">Des itinéraires à adapter.</h2></div><p className="max-w-md text-sm leading-6 text-[#C4D7CD]">Les suggestions utilisent vos intérêts enregistrés et restent des propositions ; vous pouvez les modifier à tout moment.</p></div><div className="mt-8 grid gap-4 lg:grid-cols-3">{suggestedPaths.map((path) => <article className={`path-card ${activePath === path.slug ? "path-card-active" : ""}`} key={path.slug}><span>{path.level}</span><h3>{path.title}</h3><p>{path.objective}</p><div>{path.skills.map((skill) => <small key={skill}>{skill}</small>)}</div><footer><b>{path.duration} · {path.courseSlugs.length} cours</b><button type="button" onClick={() => setActivePath(path.slug)}>{activePath === path.slug ? "Parcours choisi" : "Choisir ce parcours"} <Target size={15} /></button></footer></article>)}</div>{activeLearningPath && <div className="active-path-note"><Award size={18} /><p><b>Parcours actif : {activeLearningPath.title}.</b> Retrouvez les cours associés et suivez leur progression dans votre espace personnel.</p><Link href="/apprendre">Ouvrir les cours <ArrowRight size={16} /></Link></div>}</div></section>
    <section className="bg-[#F8F5ED] py-12"><div className="container grid gap-10 lg:grid-cols-[.86fr_1.14fr]"><div><p className="eyebrow">Compétences en pratique</p><h2 className="mt-3 font-display text-5xl leading-[.96] tracking-[-.055em]">Vos repères de progression.</h2><p className="mt-5 max-w-md leading-7 text-[#62746F]">Ces barres indiquent seulement les contenus terminés et projets consignés dans EcoCompass. Elles ne mesurent pas une compétence professionnelle et ne remplacent pas un retour humain.</p><Link href="/competences" className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-[#0E6356]">Voir la carte complète <ArrowRight size={16} /></Link></div><div className="skill-preview">{skills.map((skill) => <div key={skill.id}><div><span>{skill.label}</span><small>{skill.progress} %</small></div><i><b style={{ width: `${skill.progress}%` }} /></i><p>{skill.description}</p></div>)}</div></div></section>
    <section className="bg-white py-12"><div className="container goal-list-layout"><div><p className="eyebrow">Objectifs à court et long terme</p><h2>Garder une direction, sans rigidité.</h2><p>Ajoutez des objectifs quotidiens, hebdomadaires, mensuels ou de long terme. Ils restent personnels et révisables.</p></div><div><form className="goal-create" onSubmit={createGoal}><input value={goalDraft} onChange={(event) => setGoalDraft(event.target.value)} placeholder="Ex. terminer un module de statistiques" /><select value={goalTimeframe} onChange={(event) => setGoalTimeframe(event.target.value as typeof goalTimeframe)}>{timeframes.map((item) => <option key={item} value={item}>{item}</option>)}</select><button className="cta-primary" type="submit">Ajouter</button></form><div className="goal-list">{goals.map((goal) => <article className={goal.completed ? "goal-done" : ""} key={goal.id}><button type="button" onClick={() => toggleGoal(goal.id)}>{goal.completed ? <CheckCircle2 size={17} /> : <Circle size={17} />}</button><span>{goal.timeframe}</span><b>{goal.title}</b><button type="button" onClick={() => removeGoal(goal.id)} aria-label="Supprimer l’objectif"><Trash2 size={15} /></button></article>)}</div></div></div></section>
  </SiteShell>;
}
