/** Design: Atlas académique vivant — aucune opportunité active n’est inventée ; seuls les portails officiels sont proposés à la consultation. */
import { useMemo, useState } from "react";
import { ArrowUpRight, BadgeCheck, CalendarClock, ExternalLink, Search, ShieldAlert } from "lucide-react";
import SiteShell from "@/components/SiteShell";
import PageHero from "@/components/PageHero";
import AtlasTrail from "@/components/AtlasTrail";
import { opportunityPortals } from "@/data/ecosystemV4";

export default function Opportunities() {
  const [scope, setScope] = useState("Tous"); const [audience, setAudience] = useState("Tous"); const [query, setQuery] = useState("");
  const list = useMemo(() => { const term = query.trim().toLowerCase(); return opportunityPortals.filter((item) => (scope === "Tous" || item.scope === scope) && (audience === "Tous" || item.audiences.includes(audience)) && (!term || [item.title, item.organisation, item.description, ...item.themes].join(" ").toLowerCase().includes(term))); }, [audience, query, scope]);
  return <SiteShell><PageHero variant="page-hero-opportunities" eyebrow="Opportunités · liens à vérifier" title={<>Chercher une occasion,<br /><em>vérifier avant d’agir.</em></>} description="EcoCompass présente ici des portails institutionnels officiels, pas des offres recopiées ni garanties. Vérifiez toujours l’intitulé, le public concerné, le pays, la date limite et les conditions sur la source avant toute candidature." aside={<div className="opportunity-hero-note"><BadgeCheck size={22} /><b>Pas de fausses annonces</b><span>Une opportunité active exige une source officielle et une date contrôlable ; sinon, elle n’est pas affichée comme offre.</span></div>} /><AtlasTrail label="Du projet à une source vérifiable" tone="ochre" steps={[{ label: "Profil", href: "/mon-ecocompass", note: "clarifier" }, { label: "Compétences", href: "/marche-competences", note: "développer" }, { label: "Métiers", href: "/metiers", note: "explorer" }, { label: "Opportunités", href: "/opportunites", note: "chercher" }, { label: "Source", note: "vérifier" }]} />
    <section className="bg-[#F8F5ED] py-10 lg:py-14"><div className="container"><div className="opportunity-filter"><label><Search size={18} /><span className="sr-only">Rechercher un portail</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Rechercher économie, data, développement…" /></label><div>{["Tous", "Togo", "Afrique", "International"].map((item) => <button type="button" key={item} className={scope === item ? "filter-pill filter-pill-active" : "filter-pill"} onClick={() => setScope(item)}>{item}</button>)}</div><div>{["Tous", "Étudiant", "Jeune diplômé", "Professionnel"].map((item) => <button type="button" key={item} className={audience === item ? "opportunity-audience-active" : ""} onClick={() => setAudience(item)}>{item}</button>)}</div></div><div className="opportunity-alert"><ShieldAlert size={19} /><p><b>Statut de cette page :</b> elle présente des portails officiels à consulter. Aucune carte ci-dessous ne signifie qu’une candidature est actuellement ouverte ou que vous êtes éligible.</p></div><div className="opportunity-grid">{list.map((item) => <article key={item.id}><header><span>{item.scope}</span><b>{item.status}</b></header><h2>{item.title}</h2><p className="opportunity-org">{item.organisation}</p><p>{item.description}</p><div>{item.themes.map((theme) => <span key={theme}>{theme}</span>)}</div><footer><p><CalendarClock size={15} /> {item.deadline}</p><small>Source : {item.source} · vérifiée le {item.checkedAt}</small><a href={item.officialUrl} target="_blank" rel="noreferrer">Consulter le portail <ArrowUpRight size={15} /></a></footer></article>)}</div>{!list.length && <div className="empty-state"><ExternalLink size={27} /><h2>Aucun portail officiel ne correspond à ce filtre.</h2><p>Retirez un critère ou consultez une autre zone géographique. Les offres locales seront ajoutées seulement après vérification de leur source et de leur date.</p></div>}</div></section></SiteShell>;
}
