/**
 * Design: Atlas académique vivant — le portfolio rassemble des traces réelles de pratique locale, sans se faire passer pour une page publique ou une certification.
 */
import { useMemo, useState } from "react";
import { ArrowRight, BookOpenCheck, BriefcaseBusiness, CheckCircle2, FileLock2, FolderKanban, GraduationCap, PencilLine, Share2, Sparkles } from "lucide-react";
import { Link } from "wouter";
import SiteShell from "@/components/SiteShell";
import PageHero from "@/components/PageHero";
import AtlasTrail from "@/components/AtlasTrail";
import { useLearning } from "@/contexts/LearningContext";
import { guidedProjects, skillDefinitions, courseSkills } from "@/data/v3";

export default function Portfolio() {
  const { profile, projects, completed, portfolioIntro, setPortfolioIntro, awardBadge } = useLearning();
  const [editing, setEditing] = useState(!portfolioIntro);
  const [draft, setDraft] = useState(portfolioIntro);
  const portfolioProjects = projects.filter((project) => project.portfolio || project.status === "terminé");
  const skills = useMemo(() => skillDefinitions.filter((skill) => completed.some((slug) => courseSkills[slug]?.includes(skill.id)) || portfolioProjects.some((project) => guidedProjects.find((item) => item.slug === project.templateSlug)?.skills.some((value) => value.toLowerCase().includes(skill.label.toLowerCase().split(" ")[0])))), [completed, portfolioProjects]);
  const saveIntro = () => { setPortfolioIntro(draft); if (draft.trim()) awardBadge("Premier portfolio"); setEditing(false); };
  return <SiteShell>
    <PageHero variant="page-hero-projects" eyebrow="Présentation personnelle locale" title={<>Mon portfolio,<br /><em>mes réalisations.</em></>} description="Votre portfolio rassemble les traces de pratique que vous choisissez d’enregistrer. Il reste privé dans ce navigateur : vous gardez la main sur ce qui y apparaît." aside={<div className="projects-hero-note"><FileLock2 size={22} /><b>{portfolioProjects.length} réalisation{portfolioProjects.length !== 1 ? "s" : ""}</b><span>Les projets visibles ici proviennent d’actions que vous avez explicitement terminées et ajoutées au portfolio.</span></div>} />
    <AtlasTrail label="Projet terminé → résultat → portfolio" tone="ochre" steps={[{ label: "Cours", href: "/apprendre", note: "apprendre" }, { label: "EcoLab", href: "/ecolab", note: "observer" }, { label: "Projet", href: "/projets", note: "réaliser" }, { label: "Portfolio", href: "/portfolio", note: "présenter" }, { label: "Portails", href: "/opportunites", note: "vérifier" }]} />
    <section className="bg-[#F8F5ED] py-12"><div className="container portfolio-v5-layout"><aside><p className="eyebrow">Identité de portfolio</p><h2>{profile.name || "Mon parcours EcoCompass"}</h2><span>{profile.level}</span><p><b>Objectif :</b> {profile.goal || "à définir"}</p>{profile.specialization && <p><b>Spécialisation :</b> {profile.specialization}</p>}<div><BookOpenCheck size={16} /><span>{completed.length} cours terminés</span></div><div><FolderKanban size={16} /><span>{portfolioProjects.length} projets présentés</span></div><div><Sparkles size={16} /><span>{skills.length} compétences liées à des actions</span></div></aside><main><div className="portfolio-intro-heading"><div><p className="eyebrow">Présentation</p><h2>Une introduction simple et personnelle.</h2></div><button type="button" onClick={() => { setDraft(portfolioIntro); setEditing((value) => !value); }}><PencilLine size={15} /> {editing ? "Fermer" : "Modifier"}</button></div>{editing ? <div className="portfolio-intro-edit"><textarea value={draft} onChange={(event) => setDraft(event.target.value)} placeholder="Présentez ce que vous apprenez, votre objectif et le type de problèmes qui vous intéressent…" /><button className="cta-primary" type="button" onClick={saveIntro}>Enregistrer la présentation</button></div> : <p className="portfolio-intro-copy">{portfolioIntro || "Ajoutez une courte présentation pour donner un contexte à vos réalisations."}</p>}<div className="portfolio-v5-skills"><p className="eyebrow">Compétences reliées aux actions</p>{skills.length ? skills.map((skill) => <span key={skill.id}>{skill.label}</span>) : <Link href="/apprendre">Terminer un cours pour établir un premier repère <ArrowRight size={15} /></Link>}</div></main></div></section>
    <section className="bg-white py-12 lg:py-16"><div className="container"><div className="section-heading"><div><p className="eyebrow">Réalisations</p><h2>Projets ajoutés à mon portfolio.</h2></div><p>Chaque fiche indique une trace d’apprentissage locale. Elle ne constitue pas une certification, une expérience d’emploi ni une évaluation externe.</p></div>{portfolioProjects.length ? <div className="portfolio-v5-grid">{portfolioProjects.map((item) => { const template = guidedProjects.find((project) => project.slug === item.templateSlug); return <article key={item.id}><header><FolderKanban size={18} /><span>Terminé</span></header><h3>{item.title}</h3><p>{template?.objective}</p><div><b>Livrable attendu</b><span>{item.deliverable || template?.expected}</span></div>{item.reflection && <blockquote>« {item.reflection} »</blockquote>}<Link href="/projets">Revoir le projet <ArrowRight size={15} /></Link></article>; })}</div> : <div className="portfolio-v5-empty"><FolderKanban size={26} /><h3>Votre portfolio se construit avec des réalisations concrètes.</h3><p>Terminez un projet guidé dans EcoLab ou Mes projets, puis choisissez de l’ajouter ici. Une visite de page ne crée jamais une réalisation.</p><Link href="/projets" className="cta-primary">Choisir un projet <ArrowRight size={16} /></Link></div>}</div></section>
    <section className="bg-[#14333A] py-12 text-white"><div className="container portfolio-share-note"><Share2 size={24} /><div><p className="eyebrow">Partage du portfolio</p><h2>Votre portfolio reste privé.</h2><p>Vos réalisations restent dans ce navigateur. Avant de les utiliser dans une candidature ou une démarche, relisez vos analyses, vérifiez les sources citées et choisissez vous-même ce que vous souhaitez présenter.</p></div><Link href="/opportunites" className="cta-light"><BriefcaseBusiness size={17} /> Préparer mes démarches</Link></div></section>
  </SiteShell>;
}
