/** Design: Atlas académique vivant — profils-types et simulations pédagogiques, sans les faire passer pour des témoignages ou emplois réels. */
import { useState } from "react";
import { ArrowRight, BriefcaseBusiness, BrainCircuit, ChartNoAxesCombined, ClipboardCheck, Lightbulb, MonitorCog } from "lucide-react";
import { Link } from "wouter";
import SiteShell from "@/components/SiteShell";
import PageHero from "@/components/PageHero";
import AtlasTrail from "@/components/AtlasTrail";

const profiles = [
  { title: "Économiste — profil de travail", label: "Analyse et politiques", missions: ["Lire des indicateurs et documents", "Formuler des hypothèses prudentes", "Préparer une note ou une présentation"], tools: ["Tableur", "Notes de synthèse", "Graphiques"], environment: "Équipe d’étude, institution, recherche ou conseil selon l’organisation.", href: "/metiers/economiste" },
  { title: "Data analyst — profil de travail", label: "Données et visualisation", missions: ["Préparer des données", "Vérifier définitions et qualité", "Présenter un résultat compréhensible"], tools: ["Tableur", "SQL", "Visualisation"], environment: "Équipe data, entreprise, service public ou projet selon le contexte.", href: "/metiers/data-analyst" },
  { title: "Analyste financier — profil de travail", label: "Finance et décisions", missions: ["Lire un dossier ou un budget", "Comparer des options et contraintes", "Documenter une recommandation"], tools: ["Tableur", "Reporting", "Documentation financière"], environment: "Entreprise, banque, cabinet ou institution financière selon le rôle.", href: "/metiers/analyste-financier" },
];
const scenarios = [
  { id: "inflation", role: "Vous êtes analyste économique dans une institution publique.", prompt: "Une note indique une hausse de l’indice des prix. Quelle information est la plus utile à vérifier avant d’en tirer une conclusion ?", choices: ["La période, le panier concerné et la source de l’indice", "Une seule réaction observée autour de vous", "Le titre le plus partagé sur les réseaux"], answer: 0, explanation: "Avant toute interprétation, une série demande une période, une définition, une unité, une méthode et une source. Une variation observée ne suffit pas à expliquer ses causes." },
  { id: "budget", role: "Vous êtes analyste de budget dans une organisation.", prompt: "Un écart apparaît entre un budget prévu et une dépense réalisée. Quelle première démarche est la plus solide ?", choices: ["Comparer les lignes, la période et l’activité concernée", "Conclure que le projet a échoué", "Modifier le budget sans en parler"], answer: 0, explanation: "Un écart est un signal à documenter : contexte, période, postes concernés et éventuels changements d’activité doivent être examinés avant de proposer une option." },
  { id: "projet", role: "Vous êtes chargé de suivi-évaluation sur un projet territorial.", prompt: "Un indicateur progresse moins vite que prévu. Quelle question aide le plus à commencer l’analyse ?", choices: ["Comment est défini et collecté l’indicateur, et dans quel contexte ?", "Quel partenaire doit être considéré responsable immédiatement ?", "Peut-on retirer l’indicateur du rapport ?"], answer: 0, explanation: "La définition, la méthode de collecte, la période et le contexte sont nécessaires avant d’attribuer une cause ou d’en tirer une décision." },
];

export default function ProfessionalScenarios() {
  const [selected, setSelected] = useState(scenarios[0].id); const [answer, setAnswer] = useState<number | null>(null);
  const scenario = scenarios.find((item) => item.id === selected) || scenarios[0];
  const changeScenario = (id: string) => { setSelected(id); setAnswer(null); };
  return <SiteShell><PageHero variant="page-hero-professional" eyebrow="Découvrir les professionnels · simulations" title={<>Voir le travail,<br /><em>raisonner dans le rôle.</em></>} description="Ces profils sont des situations pédagogiques composites, pas des témoignages individuels. Ils servent à identifier des missions, outils, questions et limites possibles dans des rôles liés à l’économie." aside={<div className="professional-hero-note"><BrainCircuit size={22} /><b>Des situations, pas des certitudes</b><span>Les missions et environnements varient selon les organisations, projets, territoires et responsabilités.</span></div>} /><AtlasTrail label="Du métier à une démarche de travail" tone="night" steps={[{ label: "Métier", href: "/metiers", note: "explorer" }, { label: "Missions", note: "observer" }, { label: "Données", href: "/ecolab", note: "lire" }, { label: "Décision", note: "raisonner" }, { label: "Projet", href: "/projets", note: "pratiquer" }]} />
    <section className="bg-[#F8F5ED] py-11 lg:py-15"><div className="container"><div className="section-heading"><div><p className="eyebrow">Profils de travail</p><h2>Des journées-types, à nuancer.</h2></div><p>Chaque carte décrit des activités fréquentes possibles. Elle ne représente ni une personne réelle, ni une journée identique dans toutes les organisations.</p></div><div className="professional-grid">{profiles.map((profile) => <article key={profile.title}><header><BriefcaseBusiness size={19} /><span>{profile.label}</span></header><h3>{profile.title}</h3><p className="professional-label">Missions possibles</p><ul>{profile.missions.map((mission) => <li key={mission}>{mission}</li>)}</ul><div><p><MonitorCog size={14} /> Outils</p>{profile.tools.map((tool) => <span key={tool}>{tool}</span>)}</div><footer><p>{profile.environment}</p><Link href={profile.href}>Voir la fiche métier <ArrowRight size={15} /></Link></footer></article>)}</div></div></section>
    <section className="bg-white py-11 lg:py-15"><div className="container professional-sim-layout"><aside><p className="eyebrow">Simulations professionnelles</p><h2>Quelle information regarder en premier ?</h2><p>Choisissez un scénario puis formulez une première réponse. L’explication rappelle une démarche de lecture ; elle ne remplace pas une analyse complète.</p>{scenarios.map((item, index) => <button type="button" key={item.id} className={scenario.id === item.id ? "professional-sim-active" : ""} onClick={() => changeScenario(item.id)}><span>0{index + 1}</span>{item.role}</button>)}</aside><main><header><ChartNoAxesCombined size={20} /><p>{scenario.role}</p></header><h3>{scenario.prompt}</h3><div className="professional-answers">{scenario.choices.map((choice, index) => <button type="button" key={choice} className={answer === index ? (index === scenario.answer ? "professional-answer-good" : "professional-answer-selected") : ""} onClick={() => setAnswer(index)}><b>{String.fromCharCode(65 + index)}</b>{choice}</button>)}</div>{answer !== null && <div className="professional-explanation"><Lightbulb size={18} /><p>{scenario.explanation}</p></div>}<Link href="/ecolab" className="professional-next"><ClipboardCheck size={17} /> Continuer dans EcoLab <ArrowRight size={16} /></Link></main></div></section>
  </SiteShell>;
}
