/**
 * Design: Atlas académique vivant — un projet transforme une notion en démarche observable, sans simuler une production professionnelle.
 */
import { useState } from "react";
import { ArrowRight, CheckCircle2, ClipboardCheck, Eye, FolderKanban, Lightbulb, PlusCircle, RotateCcw, Sparkles } from "lucide-react";
import { Link } from "wouter";
import SiteShell from "@/components/SiteShell";
import PageHero from "@/components/PageHero";
import AtlasTrail from "@/components/AtlasTrail";
import FavoriteButton from "@/components/FavoriteButton";
import { useLearning } from "@/contexts/LearningContext";
import { guidedProjects } from "@/data/v3";

const options = ["Une seule cause explique toujours l’évolution.", "Je commence par décrire la série et par noter ce que je dois encore vérifier.", "Le dernier point suffit pour conclure sur toute la période.", "Un graphique de démonstration permet une prédiction fiable."];

export default function Projects() {
  const { projects, saveProject } = useLearning();
  const [selected, setSelected] = useState(guidedProjects[0].slug);
  const [choice, setChoice] = useState<number | null>(null);
  const [showExplanation, setShowExplanation] = useState(false);
  const [reflection, setReflection] = useState("");
  const project = guidedProjects.find((item) => item.slug === selected) || guidedProjects[0];
  const saved = projects.find((item) => item.templateSlug === project.slug);
  const complete = () => saveProject({ id: saved?.id, templateSlug: project.slug, title: project.title, completedAt: new Date().toLocaleDateString("fr-FR", { year: "numeric", month: "long", day: "numeric" }), reflection });
  return <SiteShell>
    <PageHero variant="page-hero-projects" eyebrow="Pratique guidée · portfolio local" title={<>Mes projets,<br /><em>mes premières analyses.</em></>} description="Choisissez une enquête guidée, suivez ses étapes et gardez une trace de votre réflexion. Les projets restent locaux à cet appareil et servent à documenter un apprentissage, pas à certifier un niveau." aside={<div className="projects-hero-note"><FolderKanban size={22} /><b>{projects.length} projet{projects.length !== 1 ? "s" : ""} enregistré{projects.length !== 1 ? "s" : ""}</b><span>Vos réalisations s’ajoutent à votre portfolio personnel au fil de votre pratique.</span></div>} />
    <AtlasTrail label="Du cours au portfolio" tone="ochre" steps={[{ label: "Notion", href: "/apprendre", note: "comprendre" }, { label: "Question", href: "/cas", note: "problématiser" }, { label: "Donnée", href: "/ecolab", note: "observer" }, { label: "Projet", href: "/projets", note: "appliquer" }, { label: "Portfolio", note: "documenter" }]} />
    <section className="bg-[#F8F5ED] py-10 lg:py-14"><div className="container"><div className="project-selector"><div><p className="eyebrow">Choisir une pratique</p><h2>Un projet, une question économique.</h2></div><div>{guidedProjects.map((item, index) => <button key={item.slug} type="button" onClick={() => { setSelected(item.slug); setChoice(null); setShowExplanation(false); setReflection(""); }} className={selected === item.slug ? "project-selected" : ""}><span>0{index + 1}</span><b>{item.title}</b><small>{item.category}</small></button>)}</div></div>
      <div className="project-workspace"><main><div className="project-context"><div><p className="eyebrow">{project.category}</p><h1>{project.title}</h1><p>{project.objective}</p></div><FavoriteButton item={{ id: project.slug, type: "project", title: project.title, href: "/projets" }} /></div><div className="project-data-note"><Eye size={17} /><div><b>Données et cadre</b><p>{project.data}</p></div></div><div className="project-questions"><p className="eyebrow">Mode apprenant</p><h2>Avant l’explication, quelle démarche est la plus rigoureuse ?</h2><div>{options.map((option, index) => <button type="button" className={choice === index ? (index === 1 ? "choice-correct" : "choice-selected") : ""} onClick={() => { setChoice(index); setShowExplanation(false); }} key={option}><span>{String.fromCharCode(65 + index)}</span>{option}</button>)}</div>{choice !== null && <button type="button" className="show-explanation" onClick={() => setShowExplanation(true)}>Voir l’explication <Lightbulb size={16} /></button>}{showExplanation && <div className="project-explanation"><Sparkles size={17} /><p><b>La démarche B est la plus prudente.</b> Une première analyse sépare l’observation de l’explication, puis précise les informations à vérifier. Les autres formulations tirent une conclusion trop rapide à partir d’un seul support.</p></div>}</div><div className="project-reflection"><p className="eyebrow">Votre trace d’apprentissage</p><label>En quelques phrases, notez ce que vous observez, votre hypothèse et une limite à vérifier.<textarea value={reflection} onChange={(event) => setReflection(event.target.value)} placeholder="Ex. La série monte après… Je me demande si… La limite est…" /></label><button className="cta-primary" type="button" onClick={complete}><ClipboardCheck size={17} /> {saved ? "Mettre à jour mon projet" : "Ajouter à mon portfolio"}</button>{saved && <span><CheckCircle2 size={16} /> Projet enregistré le {saved.completedAt}</span>}</div></main><aside className="project-steps"><p className="eyebrow">Étapes de l’enquête</p>{project.steps.map((step, index) => <div key={step}><span>0{index + 1}</span><p>{step}</p></div>)}<section><b>Questions à garder ouvertes</b>{project.questions.map((question) => <p key={question}>· {question}</p>)}</section><Link href={`/apprendre/${project.courseSlug}`}>Revoir le cours associé <ArrowRight size={16} /></Link></aside></div></div></section>
    <section className="bg-white py-12 lg:py-16"><div className="container"><div className="section-heading"><div><p className="eyebrow">Portfolio personnel</p><h2>Mes projets EcoCompass</h2></div><p>Ce portfolio est privé et local. Il permet de conserver des traces de pratique ; il ne propose pas de partage public à ce stade.</p></div>{projects.length ? <div className="portfolio-grid">{projects.map((item) => { const source = guidedProjects.find((projectItem) => projectItem.slug === item.templateSlug); return <article key={item.id}><div><FolderKanban size={18} /><span>{item.completedAt}</span></div><h3>{item.title}</h3><p>{source?.skills.join(" · ")}</p>{item.reflection && <blockquote>« {item.reflection} »</blockquote>}<button type="button" onClick={() => { setSelected(item.templateSlug); setReflection(item.reflection || ""); window.scrollTo({ top: 0, behavior: "smooth" }); }}><RotateCcw size={15} /> Reprendre ce projet</button></article>; })}</div> : <div className="portfolio-empty"><PlusCircle size={25} /><h3>Votre portfolio commence avec une première enquête.</h3><p>Choisissez un projet guidé ci-dessus, notez votre lecture et enregistrez-la localement.</p></div>}</div></section>
  </SiteShell>;
}
