/**
 * Design: Atlas académique vivant — les fiches express condensent une notion sans effacer ses nuances ni ses sources.
 */
import { useState } from "react";
import { ArrowRight, BookOpenCheck, Lightbulb, ListChecks } from "lucide-react";
import { Link } from "wouter";
import SiteShell from "@/components/SiteShell";
import PageHero from "@/components/PageHero";

const sheets = [
  { slug: "inflation", title: "Inflation — fiche express", category: "Prix", definition: "Hausse générale et durable des prix, étudiée à partir d’un panier et d’une méthode précise.", causes: ["Coûts de production ou transport", "Demande supérieure à l’offre disponible", "Variations de prix importés ou de monnaie"], effects: ["Pouvoir d’achat", "Budget des ménages", "Décisions d’épargne et d’investissement"], example: "Si le panier de consommation d’un ménage devient plus coûteux alors que le revenu ne change pas, son pouvoir d’achat peut diminuer.", indicators: "Indice de prix, période, zone, composition du panier et organisme producteur.", policies: "Observer les causes et publics concernés avant de choisir un levier. Les effets des réponses possibles doivent ensuite être suivis.", href: "/apprendre/inflation-et-pouvoir-d-achat" },
  { slug: "pib", title: "PIB et croissance — fiche express", category: "Indicateurs", definition: "Le PIB mesure une valeur de production sur un territoire pendant une période. La croissance décrit son évolution.", causes: ["Production par secteur", "Investissement", "Consommation, échanges et productivité"], effects: ["Activité économique", "Revenus et emplois, selon le contexte", "Capacité de financement public ou privé"], example: "Une hausse de production peut faire progresser le PIB, sans renseigner à elle seule la répartition des revenus ou la qualité de vie.", indicators: "Valeur, année, unité, prix courants ou constants, pays et source.", policies: "Lire la croissance avec d’autres repères : emploi, services, inégalités, environnement et structure des secteurs.", href: "/apprendre/pib-et-croissance" },
  { slug: "offre-demande", title: "Offre et demande — fiche express", category: "Marché", definition: "Deux repères pour étudier les quantités que vendeurs et acheteurs souhaitent proposer ou acquérir selon les conditions et les prix.", causes: ["Revenus et besoins", "Coûts, techniques et intrants", "Information, alternatives et règles"], effects: ["Quantités échangées", "Pressions sur les prix", "Décisions de production ou d’achat"], example: "Une hausse du coût du transport peut modifier les conditions d’offre d’un produit, tandis que les besoins des acheteurs restent présents.", indicators: "Prix, quantités, période, lieu, qualité du produit et conditions de marché.", policies: "Ne pas déduire une cause unique à partir d’un prix : observer les quantités, coûts et contexte.", href: "/apprendre/offre-et-demande" },
  { slug: "budget", title: "Budget et épargne — fiche express", category: "Finance", definition: "Un budget organise des ressources disponibles et des usages possibles. L’épargne correspond à la part non dépensée immédiatement.", causes: ["Niveau et régularité du revenu", "Dépenses essentielles", "Objectifs, imprévus et accès aux services financiers"], effects: ["Capacité à faire face à un imprévu", "Arbitrages de consommation", "Possibilité de financer un projet"], example: "Mettre une partie d’un revenu de côté pour financer une formation constitue une forme d’épargne.", indicators: "Revenus, dépenses par poste, période de référence et type de dépenses.", policies: "Comparer les options, prévoir les imprévus et éviter de conclure qu’un modèle de budget convient à tous les ménages.", href: "/economie-reelle" },
];

export default function RevisionSheets() {
  const [selected, setSelected] = useState(sheets[0]);
  return <SiteShell>
    <PageHero variant="page-hero-sheets" eyebrow="Réviser rapidement" title={<>Des fiches express<br />pour <em>retenir l’essentiel.</em></>} description="Une fiche rassemble définition, causes possibles, conséquences, exemple, indicateurs et réponses à explorer. Elle aide à réviser, mais ne remplace ni un cours complet ni la lecture des sources." aside={<div className="sheets-hero-note"><BookOpenCheck size={21} /><b>{sheets.length} fiches de départ</b><span>Une structure stable pour reprendre une notion en quelques minutes.</span></div>} />
    <section className="bg-[#F8F5ED] py-12 lg:py-16"><div className="container grid gap-6 lg:grid-cols-[290px_minmax(0,1fr)]"><aside className="sheets-index"><p className="eyebrow">Choisir une fiche</p><div className="mt-4 grid gap-2">{sheets.map((sheet) => <button type="button" key={sheet.slug} onClick={() => setSelected(sheet)} className={`sheet-index-item ${selected.slug === sheet.slug ? "sheet-index-item-active" : ""}`}><small>{sheet.category}</small><b>{sheet.title}</b></button>)}</div></aside><article className="revision-sheet"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="eyebrow">{selected.category}</p><h1>{selected.title}</h1></div><span className="sheet-stamp">À RETENIR</span></div><section className="sheet-definition"><p className="eyebrow">Définition</p><p>{selected.definition}</p></section><div className="sheet-grid"><section><ListChecks size={19} /><h2>Causes ou facteurs à explorer</h2><ul>{selected.causes.map((item) => <li key={item}>{item}</li>)}</ul></section><section><Lightbulb size={19} /><h2>Conséquences possibles</h2><ul>{selected.effects.map((item) => <li key={item}>{item}</li>)}</ul></section></div><section className="sheet-example"><p className="eyebrow">Exemple</p><p>{selected.example}</p></section><div className="sheet-grid"><section><p className="eyebrow">Indicateurs à vérifier</p><p>{selected.indicators}</p></section><section><p className="eyebrow">Réponses à explorer</p><p>{selected.policies}</p></section></div><Link href={selected.href} className="next-course"><span><small>Approfondir la notion</small><b>Voir le contenu associé</b></span><ArrowRight size={20} /></Link></article></div></section>
  </SiteShell>;
}
