/** Design: Atlas académique vivant — les compétences sont des repères de progression pédagogique, non des certifications. */
import { ArrowRight, BookOpen, BriefcaseBusiness, CircleCheckBig, Compass, FolderKanban } from "lucide-react";
import { Link } from "wouter";
import SiteShell from "@/components/SiteShell";
import PageHero from "@/components/PageHero";
import AtlasTrail from "@/components/AtlasTrail";
import { useLearning } from "@/contexts/LearningContext";
import { careers, courses } from "@/data/ecocompass";
import { courseSkills, guidedProjects, skillDefinitions } from "@/data/v3";

const careerMap: Record<string, string[]> = { economie: ["economiste", "analyste-economique", "analyste-de-politiques-publiques"], macro: ["economiste", "analyste-economique"], donnees: ["data-analyst", "econometre", "statisticien"], finance: ["analyste-financier", "analyste-bancaire", "analyste-credit"], developpement: ["specialiste-du-developpement", "charge-de-suivi-evaluation"], communication: ["charge-detudes", "consultant", "business-analyst"] };

export default function Skills() {
  const { completed, projects } = useLearning();
  const skillRows = skillDefinitions.map((skill) => { const courseMatches = courses.filter((course) => courseSkills[course.slug]?.includes(skill.id)); const done = completed.filter((slug) => courseSkills[slug]?.includes(skill.id)).length; const projectMatches = guidedProjects.filter((project) => project.skills.some((item) => item.toLowerCase().includes(skill.label.toLowerCase().split(" ")[0]))); const projectDone = projects.filter((project) => projectMatches.some((item) => item.slug === project.templateSlug)).length; const progress = Math.min(100, done * 18 + projectDone * 14); return { ...skill, courseMatches, done, projectMatches, projectDone, progress, careers: careers.filter((career) => careerMap[skill.id]?.includes(career.slug)) }; });
  return <SiteShell><PageHero variant="page-hero-skills" eyebrow="Compétences · progression pédagogique" title={<>Mes compétences,<br /><em>en construction.</em></>} description="Cette carte relie les cours terminés et les projets enregistrés à des capacités à pratiquer. Elle constitue un repère d’apprentissage local ; elle ne délivre aucune certification professionnelle." aside={<div className="skills-hero-note"><Compass size={22} /><b>De la notion à la pratique</b><span>Un cours aide à comprendre. Un projet aide à appliquer. Une compétence se développe dans la durée.</span></div>} /><AtlasTrail label="Des activités aux pistes professionnelles" steps={[{ label: "Cours", href: "/apprendre", note: "connaissances" }, { label: "EcoLab", href: "/ecolab", note: "observation" }, { label: "Projets", href: "/projets", note: "application" }, { label: "Compétences", href: "/competences", note: "progression" }, { label: "Métiers", href: "/metiers", note: "exploration" }]} /><section className="bg-[#F8F5ED] py-10 lg:py-14"><div className="container"><div className="skill-map-intro"><div><p className="eyebrow">Votre carte de progression</p><h2>Ce que vos activités permettent de travailler.</h2></div><p>Les niveaux ci-dessous sont calculés uniquement à partir de vos activités EcoCompass enregistrées dans ce navigateur. Ils sont volontairement prudents et réversibles.</p></div><div className="skill-map-grid">{skillRows.map((skill) => <article key={skill.id}><header><div><h3>{skill.label}</h3><p>{skill.description}</p></div><b>{skill.progress} %</b></header><div className="skill-map-bar"><i style={{ width: `${skill.progress}%` }} /></div><div className="skill-map-evidence"><span><BookOpen size={15} /> {skill.done}/{skill.courseMatches.length} cours associés terminés</span><span><FolderKanban size={15} /> {skill.projectDone}/{skill.projectMatches.length} projets associés</span></div><div className="skill-map-links"><div><p>À approfondir</p>{skill.courseMatches.slice(0, 2).map((course) => <Link key={course.slug} href={`/apprendre/${course.slug}`}>{course.title}<ArrowRight size={14} /></Link>)}</div><div><p>Pistes métiers</p>{skill.careers.slice(0, 2).map((career) => <Link key={career.slug} href={`/metiers/${career.slug}`}>{career.title}<BriefcaseBusiness size={14} /></Link>)}</div></div></article>)}</div></div></section><section className="bg-white py-12"><div className="container skills-practice"><CircleCheckBig size={25} /><div><p className="eyebrow">Prochaine étape</p><h2>Une compétence devient plus visible quand vous l’appliquez.</h2><p>Choisissez une étude de cas ou un projet guidé, notez votre démarche puis revenez ici pour observer les liens créés avec vos cours et vos métiers explorés.</p></div><Link href="/projets" className="cta-primary">Choisir un projet <ArrowRight size={17} /></Link></div></section></SiteShell>;
}
