/**
 * Design: dossier éditorial professionnel — réglages simples, explicites et conservés localement par l’utilisateur.
 */
import { Accessibility, CircleGauge, Monitor, Moon, Sparkles, Sun, Type } from "lucide-react";
import { useTheme } from "@/contexts/ThemeContext";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle, SheetTrigger } from "@/components/ui/sheet";

export default function DisplayPreferences() {
  const { theme, setTheme, displayScale, setDisplayScale, motionPreference, setMotionPreference, contrastPreference, setContrastPreference } = useTheme();

  return <Sheet>
    <SheetTrigger asChild><button type="button" className="display-preferences-trigger" aria-label="Ouvrir les préférences d’affichage" title="Préférences d’affichage"><Accessibility size={18} /></button></SheetTrigger>
    <SheetContent className="preferences-sheet" side="right">
      <SheetHeader className="preferences-header"><p className="eyebrow">Préférences locales</p><SheetTitle>Votre affichage</SheetTitle><SheetDescription>Ces choix sont enregistrés uniquement dans ce navigateur.</SheetDescription></SheetHeader>
      <div className="preferences-body">
        <section aria-labelledby="theme-preference"><div className="preferences-section-heading"><span><Monitor size={17} /> Thème</span><p id="theme-preference">Choisissez le contraste qui vous convient.</p></div><div className="preference-options" role="radiogroup" aria-label="Thème"><button type="button" role="radio" aria-checked={theme === "light"} className={theme === "light" ? "preference-option preference-option-active" : "preference-option"} onClick={() => setTheme("light")}><Sun size={17} /><span><b>Mode clair</b><small>Fond clair et texte sombre</small></span></button><button type="button" role="radio" aria-checked={theme === "dark"} className={theme === "dark" ? "preference-option preference-option-active" : "preference-option"} onClick={() => setTheme("dark")}><Moon size={17} /><span><b>Mode sombre</b><small>Fond profond et texte clair</small></span></button></div></section>
        <section aria-labelledby="scale-preference"><div className="preferences-section-heading"><span><Type size={17} /> Taille de lecture</span><p id="scale-preference">Agrandissez l’interface sans modifier son contenu.</p></div><div className="preference-options" role="radiogroup" aria-label="Taille de lecture"><button type="button" role="radio" aria-checked={displayScale === "standard"} className={displayScale === "standard" ? "preference-option preference-option-active" : "preference-option"} onClick={() => setDisplayScale("standard")}><span><b>Standard</b><small>Échelle par défaut</small></span><i aria-hidden="true">Aa</i></button><button type="button" role="radio" aria-checked={displayScale === "large"} className={displayScale === "large" ? "preference-option preference-option-active" : "preference-option"} onClick={() => setDisplayScale("large")}><span><b>Lecture confortable</b><small>Texte et contrôles agrandis</small></span><i className="preference-large" aria-hidden="true">Aa</i></button></div></section>
        <section aria-labelledby="contrast-preference"><div className="preferences-section-heading"><span><CircleGauge size={17} /> Contraste</span><p id="contrast-preference">Renforcez les contours, textes secondaires et états interactifs.</p></div><div className="preference-options" role="radiogroup" aria-label="Contraste"><button type="button" role="radio" aria-checked={contrastPreference === "standard"} className={contrastPreference === "standard" ? "preference-option preference-option-active" : "preference-option"} onClick={() => setContrastPreference("standard")}><span><b>Contraste standard</b><small>Hiérarchie visuelle équilibrée</small></span></button><button type="button" role="radio" aria-checked={contrastPreference === "enhanced"} className={contrastPreference === "enhanced" ? "preference-option preference-option-active" : "preference-option"} onClick={() => setContrastPreference("enhanced")}><span><b>Contraste renforcé</b><small>Texte et contours plus affirmés</small></span></button></div></section>
        <section aria-labelledby="motion-preference"><div className="preferences-section-heading"><span><Sparkles size={17} /> Mouvements</span><p id="motion-preference">Gardez ou réduisez les animations non essentielles.</p></div><div className="preference-options" role="radiogroup" aria-label="Préférence de mouvement"><button type="button" role="radio" aria-checked={motionPreference === "standard"} className={motionPreference === "standard" ? "preference-option preference-option-active" : "preference-option"} onClick={() => setMotionPreference("standard")}><span><b>Transitions douces</b><small>Micro-interactions activées</small></span></button><button type="button" role="radio" aria-checked={motionPreference === "reduced"} className={motionPreference === "reduced" ? "preference-option preference-option-active" : "preference-option"} onClick={() => setMotionPreference("reduced")}><span><b>Réduire les mouvements</b><small>Animations désactivées</small></span></button></div></section>
      </div>
      <div className="preferences-footer"><p>Les préférences n’ont pas besoin de compte et peuvent être modifiées à tout moment.</p></div>
    </SheetContent>
  </Sheet>;
}
