/**
 * Design: Atlas académique vivant — les rappels locaux orientent sans pression, avec un choix explicite de l’utilisateur.
 */
import { useEffect, useMemo, useRef } from "react";
import { Bell, BellOff, CalendarClock, ChevronRight, CircleAlert } from "lucide-react";
import { Link } from "wouter";
import type { ActionTask } from "@/contexts/LearningContext";

function daysUntil(value: string) { const now = new Date(); now.setHours(0, 0, 0, 0); const due = new Date(`${value}T00:00:00`); return Math.round((due.getTime() - now.getTime()) / 86400000); }
export default function DueReminders({ tasks, enabled, leadDays, onToggle, onLeadDays }: { tasks: ActionTask[]; enabled: boolean; leadDays: number; onToggle: (enabled: boolean) => Promise<boolean>; onLeadDays: (days: number) => void }) {
  const seen = useRef(new Set<string>());
  const dueSoon = useMemo(() => tasks.filter((task) => !task.completed && task.dueDate).map((task) => ({ ...task, days: daysUntil(task.dueDate!) })).filter((task) => task.days <= leadDays && task.days >= 0).sort((a, b) => a.days - b.days), [tasks, leadDays]);
  useEffect(() => { if (!enabled || typeof window === "undefined" || !("Notification" in window) || Notification.permission !== "granted") return; dueSoon.forEach((task) => { if (seen.current.has(task.id)) return; new Notification("EcoCompass — échéance proche", { body: task.days === 0 ? `Aujourd’hui : ${task.title}` : `${task.days === 1 ? "Demain" : `Dans ${task.days} jours`} : ${task.title}` }); seen.current.add(task.id); }); }, [enabled, dueSoon]);
  return <section className="bg-white py-8"><div className="container due-reminders"><div className="due-reminders-head"><div><p className="eyebrow">Rappels locaux</p><h2>Vos échéances proches.</h2></div><div className="reminder-controls"><label><span>Prévenir</span><select value={leadDays} onChange={(event) => onLeadDays(Number(event.target.value))}><option value={1}>1 jour avant</option><option value={2}>2 jours avant</option><option value={3}>3 jours avant</option><option value={7}>7 jours avant</option></select></label><button type="button" className={enabled ? "reminder-enabled" : ""} onClick={() => onToggle(!enabled)}>{enabled ? <Bell size={16} /> : <BellOff size={16} />}{enabled ? "Rappels activés" : "Activer les rappels"}</button></div></div><div className="due-reminders-body"><div className="due-reminders-note"><CircleAlert size={17} /><p><span className="field-note-label">Repère de terrain · échéance</span><b>Votre choix.</b> Les rappels restent liés à cet appareil. Sans autorisation de notification, les échéances restent visibles ici lorsque vous ouvrez EcoCompass.</p></div><div className="due-reminders-list">{dueSoon.length ? dueSoon.map((task) => <article key={task.id}><span className={task.days === 0 ? "due-today" : ""}><CalendarClock size={15} />{task.days === 0 ? "Aujourd’hui" : task.days === 1 ? "Demain" : `Dans ${task.days} jours`}</span><b>{task.title}</b><Link href="/plan-action" aria-label={`Voir l’action ${task.title} dans le plan`}><ChevronRight size={17} /></Link></article>) : <div className="due-reminders-empty"><Bell size={17} /><p>Aucune action avec une échéance proche. Ajoutez une date à votre prochaine action si vous souhaitez la suivre ici.</p><Link href="/plan-action">Ajouter une échéance <ChevronRight size={15} /></Link></div>}</div></div></div></section>;
}
