/**
 * Design: Atlas académique vivant — l’historique montre des traces réelles par semaine, sans fabriquer de tendance ni de score de performance.
 */
import { CalendarRange, CheckCircle2, CircleDot, ClipboardList, FolderKanban, GraduationCap } from "lucide-react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Link } from "wouter";
import type { ActivityRecord } from "@/contexts/LearningContext";

const kindMeta = { cours: { label: "Cours", icon: GraduationCap }, quiz: { label: "Quiz", icon: CheckCircle2 }, projet: { label: "Projet", icon: FolderKanban }, action: { label: "Action", icon: ClipboardList }, objectif: { label: "Objectif", icon: CircleDot } } as const;
function monday(date: Date) { const copy = new Date(date); const day = (copy.getDay() + 6) % 7; copy.setDate(copy.getDate() - day); copy.setHours(0, 0, 0, 0); return copy; }
function iso(date: Date) { return date.toISOString().slice(0, 10); }

export default function WeeklyHistory({ activityLog }: { activityLog: ActivityRecord[] }) {
  const now = new Date();
  const weeks = Array.from({ length: 6 }, (_, index) => { const date = monday(now); date.setDate(date.getDate() - (5 - index) * 7); return { key: iso(date), label: new Intl.DateTimeFormat("fr-FR", { day: "numeric", month: "short" }).format(date), end: new Date(date.getFullYear(), date.getMonth(), date.getDate() + 6, 23, 59, 59) }; });
  const history = weeks.map((week) => { const entries = activityLog.filter((activity) => { const activityDate = new Date(activity.occurredAt); const start = new Date(`${week.key}T00:00:00`); return activityDate >= start && activityDate <= week.end; }); return { ...week, total: entries.length, entries }; });
  const total = activityLog.length;
  return <section className="bg-[#F8F5ED] py-12"><div className="container weekly-history-layout"><div className="weekly-history-intro"><p className="eyebrow">Historique de progression</p><h2>Vos traces,<br /><em>semaine après semaine.</em></h2><p>L’historique rassemble uniquement les actions réellement enregistrées depuis l’activation de ce suivi. Les semaines sans activité restent visibles, sans être interprétées comme un échec.</p><div><CalendarRange size={18} /><span>{total} trace{total > 1 ? "s" : ""} enregistrée{total > 1 ? "s" : ""}</span></div><Link href="/plan-action" className="weekly-next-trace">Créer une prochaine trace <span>→</span></Link></div><div className="weekly-history-card"><div className="weekly-history-cartouche"><span>Jalon 02 · progression</span><span>Période glissante · 6 semaines</span><span>Traces locales</span><span>Sans comparaison</span></div><div className="weekly-chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={history}><defs><linearGradient id="weeklyAtlas" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#0E6356" stopOpacity={.32} /><stop offset="100%" stopColor="#0E6356" stopOpacity={0} /></linearGradient></defs><CartesianGrid stroke="#DCE7DE" vertical={false} /><XAxis dataKey="label" tick={{ fill: "#6C7E75", fontSize: 10 }} axisLine={false} tickLine={false} /><YAxis allowDecimals={false} tick={{ fill: "#6C7E75", fontSize: 10 }} axisLine={false} tickLine={false} width={22} /><Tooltip contentStyle={{ border: "1px solid #D8E5D9", borderRadius: 0, fontSize: 12 }} cursor={{ stroke: "#0E6356", strokeDasharray: "3 3" }} /><Area type="monotone" dataKey="total" stroke="#0E6356" strokeWidth={2.5} fill="url(#weeklyAtlas)" activeDot={{ r: 4, fill: "#14333A" }} /></AreaChart></ResponsiveContainer></div><div className="weekly-details">{history.map((week) => <article key={week.key}><header><b>Semaine du {week.label}</b><span>{week.total} trace{week.total > 1 ? "s" : ""}</span></header>{week.entries.length ? <div>{week.entries.map((entry) => { const meta = kindMeta[entry.kind]; const Icon = meta.icon; return <p key={entry.id}><Icon size={13} /><span>{meta.label}</span>{entry.label}</p>; })}</div> : <small>Aucune trace enregistrée cette semaine.</small>}</article>)}</div></div></div></section>;
}
